### ISSUE TITLE
amdkfd module not on initrd by default

### ISSUE THREAD

**Issue by jamborm** [RadeonOpenCompute/ROCK-Kernel-Driver#10]
I have applied the ROCK-specific patches on top of 4.4 OpenSUSE
Tumbleweed kernel but they did not allow running HSA kernels because
that only works if andkfd module is loaded before amdgpu, which did
not happen because amdkfd was not on the initrd (modprobing amdkfd,
rebuilding initrd and rebooting worked but is of course bad).

After discussing this with Michal Marek, he came up with patch that is
now submitted upstream as
https://lists.freedesktop.org/archives/dri-devel/2016-August/116708.html
and which fixes the issue, my (experimental) SUSE RPMs work out of the
box with it.  Therefore, I'd suggest to include it in the next round
of updates (unless you get it from upstream, of course).

**Comment by arodrigx7** [comment]
Thanks for getting the discussion started to get the patch on the mailing list.

I'll keep an eye on it and pick it up once it gets merged.

**Comment by jamborm** [comment]
The patch going upstream got updated a bit:

http://www.spinics.net/lists/dri-devel/msg116699.html

**Comment by tekcomm** [comment]
The following has been tested and The KFC issue has been slated for official removal in the 4.17

http://kernel.ubuntu.com/~kernel-ppa/mainline/drm-intel-nightly/current/linux-headers-4.16.0-994_4.16.0-994.201803132200_all.deb

http://kernel.ubuntu.com/~kernel-ppa/mainline/drm-intel-nightly/current/linux-headers-4.16.0-994-lowlatency_4.16.0-994.201803132200_amd64.deb

http://kernel.ubuntu.com/~kernel-ppa/mainline/drm-intel-nightly/current/linux-image-4.16.0-994-lowlatency_4.16.0-994.201803132200_amd64.deb

********************* Please remember to add pti=off to grub unless you like a 30% loss in hashing ********

**Comment by tekcomm** [comment]
I just had to say I really miss suse......  I miss slackware even more but I end up in the end creating a frankensuseslackedgentoo ubutntu lol.

**Comment by kentrussell** [comment]
Is the issue still present on 1.8? I'll close this one since you've got the workaround defined in https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/issues/47 .
