### ISSUE TITLE
Add support for low-latency RDMA copy like Nvidia's gdrCopy

### ISSUE THREAD

**Issue by stgeke** [RadeonOpenCompute/ROCK-Kernel-Driver#101]
Is this already supported?

**Comment by fxkamd** [comment]
This is not a kernel mode driver question, but more of a user mod library/API support question.

I'm not familiar with gdrCopy. In ROCm we have RCCL, which is based on NCCL. I believe that includes support for RDMA. RDMA is also used by some MPI implementations to accelerate MPI_Send/Receive operations.
