### ISSUE TITLE
ERROR: "amdkfd_query_rdma_interface" undefined!

### ISSUE THREAD

**Issue by xliangseu-kfd** [RadeonOpenCompute/ROCK-Kernel-Driver#105]
I want to wirte a module in ubuntu 18.04 to make a GPU/FPGA peer-to-peer transfer. Actually,  I am a newbie in this field.
ROCm 3.10 is installed and my linux kernel is 4.6.0.
I have written a very simple code to test the function "amdkfd_query_rdma_interface" which is defined in "amd_rdma.h"

The code is as follows:
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#include <linux/module.h>
#include <linux/init.h>
#include "amd_rdma.h"

MODULE_LICENSE("Dual BSD/GPL");

#define AMDP2PTEST_DEVICE_NAME "amdp2ptest"

#define MSG_INFO(fmt, args ...)\
        pr_info(AMDP2PTEST_DEVICE_NAME ":" fmt, ## args)

const struct amd_rdma_interface *rdma_interface;

static int lkp_init(void)
{
        int result;

        printk(KERN_ALERT "Hello World!\n");

        result = amdkfd_query_rdma_interface(&rdma_interface);

	if (result < 0) {
		MSG_ERR("Can not get RDMA Interface (result = %d)\n", result);
		return result;
	}

	MSG_INFO("RDMA Interface %p\n",		rdma_interface);
	MSG_INFO("     get_pages %p\n",		rdma_interface->get_pages);
	MSG_INFO("     put_pages %p\n",		rdma_interface->put_pages);
	MSG_INFO("     is_gpu_address %p\n",	rdma_interface->is_gpu_address);
	MSG_INFO("     get_page_size %p\n",	rdma_interface->get_page_size);

        return 0;
}

static void lkp_cleanup(void)
{
        printk(KERN_ALERT "Bye World!\n");
}

module_init(lkp_init);
module_exit(lkp_cleanup);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

The Makefile is as follows:
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
obj-m := hello.o

RDMADIR :=/usr/src/amdgpu-3.10-27/include/drm

ccflags-y += -I$(RDMADIR)

KERNELBUILD :=/lib/modules/$(shell uname -r)/build

modules:
        make -C $(KERNELBUILD) M=$(shell pwd) modules
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

When I compile this program, the output shows some errors as follows:
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
make -C /lib/modules/5.6.0/build   M=/home/xliangseu/Documents/LD/drivers modules
make[1]: Entering directory '/usr/src/linux-5.6'
  MODPOST 1 modules
ERROR: "amdkfd_query_rdma_interface" [/home/xliangseu/Documents/LD/drivers/hello.ko] undefined!
scripts/Makefile.modpost:93: recipe for target '__modpost' failed
make[2]: *** [__modpost] Error 1
Makefile:1596: recipe for target 'modules' failed
make[1]: *** [modules] Error 2
make[1]: Leaving directory '/usr/src/linux-5.6'
Makefile:11: recipe for target 'modules' failed
make: *** [modules] Error 2
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

It seems that the function "amdkfd_query_rdma_interface" is not defined! I am sure I have included the header "amd_rdma.h" and tell the compiler where to find it. But it can't work. Maybe I missed some steps?
Anyone can tell me how I can compile it properly?

Best regard

**Comment by fxkamd** [comment]
I think the problem is that amdkfd_query_rdma_interface is not exported by the kernel but the amdgpu module, which is not part of the kernel source you're building against. So the linker can't find the symbol when you're linking your kernel module. You may need to look up the symbol dynamically using symbol_get.

**Comment by xliangseu-kfd** [comment]
> I think the problem is that amdkfd_query_rdma_interface is not exported by the kernel but the amdgpu module, which is not part of the kernel source you're building against. So the linker can't find the symbol when you're linking your kernel module. You may need to look up the symbol dynamically using symbol_get.

Thank you for your helpful information. I will try it today. 
I have a related question. Should I download the ROCK-Kernel-Driver Source code. Should I compile and install it?
My current kernel source is downloaded from kernel.org. I compiled it and installed them. 

Yesterday, I tried to compile  ROCK kernel Driver source code. 
However the recommend config command "sudo make rock-rel_defconfig" failed as follows:

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
rel_defconfig
***
*** Can't find default configuration "arch/x86/configs/rock-rel_defconfig"!
***
scripts/kconfig/Makefile:92: recipe for target 'rock-rel_defconfig' failed
make[1]: *** [rock-rel_defconfig] Error 1
Makefile:568: recipe for target 'rock-rel_defconfig' failed
make: *** [rock-rel_defconfig] Error 2
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

I have checked that there is no rock-rel_defconfig in arch/x86/configs/, actually there are these files in that place

i386_defconfig  rock-dbg_defconfig  tiny.config  x86_64_defconfig  xen.config

Any suggestions I should do? Maybe this is a wrong way. Thanks!

Best regards

**Comment by fxkamd** [comment]
The upstream kernel does not include the kfd_rdma interface. This was originally added to support a proprietary 3rd-party module. You'll need our DKMS kernel module installed (package named rock-dkms).

We don't have a rock-rel_defconfig any more, because we no longer build monolithic release kernels. This has been replaced with DKMS package installation a long time ago.

**Comment by xliangseu-kfd** [comment]
> The upstream kernel does not include the kfd_rdma interface. This was originally added to support a proprietary 3rd-party module. You'll need our DKMS kernel module installed (package named rock-dkms).
> 
> We don't have a rock-rel_defconfig any more, because we no longer build monolithic release kernels. This has been replaced with DKMS package installation a long time ago.

Thank you fxkamd.
I took you suggestion and tried to install rock-dkms in another computer.
I followed the instructions which were got from www.rocmdos.com

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
wget -qO - https://repo.radeon.com/rocm/apt/debian/rocm.gpg.key | sudo apt-key add -
echo deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ xenial main | sudo tee /etc/apt/sources.list.d/rocm.list
sudo apt-get update && sudo apt-get install compute-firmware rock-dkms
sudo update-initramfs -u
sudo reboot
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Firstly, apt can not  find computer-firmware. I thought this package is too old.
So I had to only install rock-dkms. But it failed. The log is as follows: 

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
make: Entering directory '/usr/src/linux-headers-4.15.0-126-generic'
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/main.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/symbols.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/scheduler/sched_main.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_memory.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/scheduler/sched_fence.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_ioctl.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/ttm/ttm_memory.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/scheduler/sched_entity.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_device_cgroup.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/ttm/ttm_tt.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_drm_cache.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/ttm/ttm_bo.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/ttm/ttm_bo_util.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_drm.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_drv.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/ttm/ttm_bo_vm.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_fence_array.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_device.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/ttm/ttm_module.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_fence.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_kms.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/ttm/ttm_execbuf_util.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_io.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/ttm/ttm_page_alloc.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_atombios.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/ttm/ttm_bo_manager.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_kthread.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/atombios_crtc.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/ttm/ttm_agp_backend.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_mm.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_pci.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_connectors.o
/var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_mm.c:5:44: warning: ‘struct task_struct’ declared inside parameter list will not be visible outside of this definition or declaration
 struct mm_struct* (*_kcl_mm_access)(struct task_struct *task, unsigned int mode);
                                            ^~~~~~~~~~~
/var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_mm.c:8:55: warning: ‘struct task_struct’ declared inside parameter list will not be visible outside of this definition or declaration
 static struct mm_struct * __kcl_mm_access_stub(struct task_struct *task, unsigned int mode)
                                                       ^~~~~~~~~~~
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/atom.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_perf_event.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_reservation.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_suspend.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_fence.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/ttm/ttm_page_alloc_dma.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_workqueue.o
/var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_suspend.c: In function ‘amdkcl_suspend_init’:
/var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_suspend.c:30:21: warning: comparison of distinct pointer types lacks a cast
  if (_kcl_ksys_sync != _kcl_sys_sync_stub) {
                     ^~
/var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_suspend.c:35:21: warning: comparison of distinct pointer types lacks a cast
  if (_kcl_ksys_sync != _kcl_sys_sync_stub) {
                     ^~
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_seq_file.o
/var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_pci.c: In function ‘amdkcl_pci_init’:
/var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_pci.c:103:84: warning: passing argument 2 of ‘amdkcl_fp_setup’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  _kcl_pcie_link_speed = (const unsigned char *) amdkcl_fp_setup("pcie_link_speed", _kcl_pcie_link_speed_stub);
                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_pci.c:4:0:
/var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_common.h:12:21: note: expected ‘void *’ but argument is of type ‘const unsigned char *’
 static inline void *amdkcl_fp_setup(const char *symbol, void *fp_stup)
                     ^~~~~~~~~~~~~~~
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_connector.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_backlight.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_drm_atomic_helper.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_ttm.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_drm_crtc.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_drm_fb.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_drm_modeset_lock.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_drm_modes.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_time.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_object.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/kcl_mn.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_gart.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/dma-buf/dma-resv.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_encoders.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_display.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_i2c.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_fb.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_gem.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_ring.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_cs.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_bios.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_benchmark.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_test.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/atombios_dp.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_afmt.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_trace_points.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/atombios_encoders.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_sa.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/atombios_i2c.o
  LD [M]  /var/lib/dkms/amdgpu/3.10-27/build/scheduler/amd-sched.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_dma_buf.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_vm.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_ib.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_pll.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_ucode.o
  LD [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdkcl/amdkcl.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_bo_list.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_ctx.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_sync.o
  LD [M]  /var/lib/dkms/amdgpu/3.10-27/build/ttm/amdttm.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_gtt_mgr.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_vram_mgr.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_virt.o
/var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_fb.c: In function ‘amdgpufb_create’:
/var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_fb.c:252:14: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  info->fbops = &amdgpufb_ops;
              ^
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_atomfirmware.o
/var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_bios.c: In function ‘amdgpu_read_platform_bios’:
/var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_bios.c:200:9: error: implicit declaration of function ‘pci_platform_rom’; did you mean ‘pci_map_rom’? [-Werror=implicit-function-declaration]
  bios = pci_platform_rom(adev->pdev, &size);
         ^~~~~~~~~~~~~~~~
         pci_map_rom
/var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_bios.c:200:7: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  bios = pci_platform_rom(adev->pdev, &size);
       ^
/var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_cs.c:1225:12: warning: ‘amdgpu_cs_process_syncobj_timeline_out_dep’ defined but not used [-Wunused-function]
 static int amdgpu_cs_process_syncobj_timeline_out_dep(struct amdgpu_cs_parser *p,
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_cs.c:1165:12: warning: ‘amdgpu_cs_process_syncobj_timeline_in_dep’ defined but not used [-Wunused-function]
 static int amdgpu_cs_process_syncobj_timeline_in_dep(struct amdgpu_cs_parser *p,
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_vf_error.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_sched.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_debugfs.o
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_ids.o
/var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_sa.c: In function ‘amdgpu_sa_bo_dump_debug_info’:
/var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_sa.c:391:41: warning: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 3 has type ‘unsigned int’ [-Wformat=]
    seq_printf(m, " protected by 0x%016llx on context %llu",
                                   ~~~~~~^
                                   %016x
        i->fence->seqno, i->fence->context);
        ~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
  CC [M]  /var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_gmc.o
scripts/Makefile.build:330: recipe for target '/var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_bios.o' failed
make[2]: *** [/var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu/amdgpu_bios.o] Error 1
make[2]: *** Waiting for unfinished jobs....
scripts/Makefile.build:604: recipe for target '/var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu' failed
make[1]: *** [/var/lib/dkms/amdgpu/3.10-27/build/amd/amdgpu] Error 2
Makefile:1587: recipe for target '_module_/var/lib/dkms/amdgpu/3.10-27/build' failed
make: *** [_module_/var/lib/dkms/amdgpu/3.10-27/build] Error 2
make: Leaving directory '/usr/src/linux-headers-4.15.0-126-generic'
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Do you have any suggestions on this issue? Thanks.

Best regards

**Comment by fxkamd** [comment]
The current installation instructions are at https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html.

compute-firmware is the wrong package. It doesn't exist any more with the DKMS packaging method. Try rock-dkms-firmware.

**Comment by xliangseu-kfd** [comment]
> The current installation instructions are at https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html.
> 
> compute-firmware is the wrong package. It doesn't exist any more with the DKMS packaging method. Try rock-dkms-firmware.

Thank you. I followed the instructions on the website you provided. I have installed rock-dkms.
But my program still failed compiled with
ERROR: "amdkfd_query_rdma_interface" [/home/xliangseu/Documents/LD/drivers/hello.ko] undefined!

After lsmod | grep amd , it shows that 
amdgpu               5758976  1
amd_iommu_v2           20480  1 amdgpu
amd_sched              32768  1 amdgpu
amdttm                 98304  1 amdgpu
amdkcl                 24576  2 amdttm,amdgpu
drm_kms_helper        176128  2 amdgpu,i915
drm                   516096  19 drm_kms_helper,amd_sched,amdttm,amdgpu,i915,amdkcl
i2c_algo_bit           16384  2 amdgpu,i915

So, there is no the module called 'amdkfd', instead I find the module 'amdgpu'.
How do I use the function "amdkfd_query_rdma_interface" in "/usr/src/amdgpu-3.10-27/include/drm/amd_rdma.h"?
Do you mean amdkfd_query_rdma_interface is a symbol provided by amdgpu module now?
As you mentioned, how do I  look up the symbol dynamically using symbol_get?
Thanks a lot!

**Comment by fxkamd** [comment]
Right, amdkfd is no longer a separate kernel module. It has been integrated into amdgpu since kernel version 4.20.

I think you should be able to lookup the amdkfd_query_rdma_interface function with something like this:

> static void (*query_rdma_interface)(const struct amd_rdma_interface **);
> static const struct amd_rdma_interface *rdma_ops;
> 
> int init_my_module()
> {
> 	query_rdma_interface = symbol_get(amdkfd_query_rdma_interface);
> 	if (!query_rdma_interface)
> 		return -ENODEV;
> 
> 	return query_rdma_interface(&rdma_ops);
> }
> 
> void fini_my_module()
> {
> 	if (query_rdma_interface) {
> 		symbol_put(amdkfd_query_rdma_interface);
> 		query_rdma_interface = NULL;
> 		rdma_ops = NULL;
> 	}
> }

**Comment by xliangseu-kfd** [comment]
> Right, amdkfd is no longer a separate kernel module. It has been integrated into amdgpu since kernel version 4.20.
> 
> I think you should be able to lookup the amdkfd_query_rdma_interface function with something like this:
> 
> > static void (*query_rdma_interface)(const struct amd_rdma_interface **);
> > static const struct amd_rdma_interface *rdma_ops;
> > int init_my_module()
> > {
> > query_rdma_interface = symbol_get(amdkfd_query_rdma_interface);
> > if (!query_rdma_interface)
> > return -ENODEV;
> > return query_rdma_interface(&rdma_ops);
> > }
> > void fini_my_module()
> > {
> > if (query_rdma_interface) {
> > symbol_put(amdkfd_query_rdma_interface);
> > query_rdma_interface = NULL;
> > rdma_ops = NULL;
> > }
> > }

Thank you fxkamd! 
I have modified my code as follows:

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#include <linux/module.h>
#include <linux/init.h>
#include "amd_rdma.h"

MODULE_LICENSE("Dual BSD/GPL");

#define AMDP2PTEST_DEVICE_NAME "amdp2ptest"

#define MSG_INFO(fmt, args ...) \
        pr_info(AMDP2PTEST_DEVICE_NAME ": " fmt, ## args)

static void (*query_rdma_interface)(const struct amd_rdma_interface **);
static const struct amd_rdma_interface *rdma_ops;

static int lkp_init(void)
{
    printk(KERN_ALERT "Hello World!\n");

    query_rdma_interface = symbol_get(amdkfd_query_rdma_interface);

    if (!query_rdma_interface)
        return -ENODEV;

    return query_rdma_interface(&rdma_ops);
}

static void lkp_cleanup(void)
{
    printk(KERN_ALERT "Bye World!\n");
    if (query_rdma_interface) {
        symbol_put(amdkfd_query_rdma_interface);
        query_rdma_interface = NULL;
        rdma_ops = NULL;
    }
}

module_init(lkp_init);
module_exit(lkp_cleanup);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

However, it failed in compilation as follows:

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

make -C /lib/modules/5.4.0/build   M=/home/xliangseu/Documents/LD/hello modules
make[1]: Entering directory '/usr/src/linux-5.4'
  CC [M]  /home/xliangseu/Documents/LD/hello/hello.o
/home/xliangseu/Documents/LD/hello/hello.c: In function ‘lkp_init’:
/home/xliangseu/Documents/LD/hello/hello.c:19:26: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
     query_rdma_interface = symbol_get(amdkfd_query_rdma_interface);
                          ^
/home/xliangseu/Documents/LD/hello/hello.c:24:12: error: void value not ignored as it ought to be
     return query_rdma_interface(&rdma_ops);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/xliangseu/Documents/LD/hello/hello.c:25:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
cc1: some warnings being treated as errors
scripts/Makefile.build:265: recipe for target '/home/xliangseu/Documents/LD/hello/hello.o' failed
make[2]: *** [/home/xliangseu/Documents/LD/hello/hello.o] Error 1
Makefile:1652: recipe for target '/home/xliangseu/Documents/LD/hello' failed
make[1]: *** [/home/xliangseu/Documents/LD/hello] Error 2
make[1]: Leaving directory '/usr/src/linux-5.4'
Makefile:12: recipe for target 'modules' failed
make: *** [modules] Error 2

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

It seems these two warnings can not be ignored. Please help me to get this code work. 
Thank you very much!

**Comment by xliangseu-kfd** [comment]
Oh, it works, by changing from
query_rdma_interface = symbol_get(amdkfd_query_rdma_interface)
to
query_rdma_interface = (void(*)(const struct amd_rdma_interface **))symbol_get(amdkfd_query_rdma_interface);

I can really access 'amdkfd_query_rdma_interface'. Thank you fxkamd!

**Comment by fxkamd** [comment]
> > static void (*query_rdma_interface)(const struct amd_rdma_interface **);

My mistake. Change "void" to "int" here to fix the compiler warning.

> > static const struct amd_rdma_interface *rdma_ops;
> > int init_my_module()
> > {
> > query_rdma_interface = symbol_get(amdkfd_query_rdma_interface);
> > if (!query_rdma_interface)
> > return -ENODEV;
> > return query_rdma_interface(&rdma_ops);
> > }
> > void fini_my_module()
> > {
> > if (query_rdma_interface) {
> > symbol_put(amdkfd_query_rdma_interface);
> > query_rdma_interface = NULL;
> > rdma_ops = NULL;
> > }
> > }

**Comment by xliangseu-kfd** [comment]
Yes, it is really good. 
Thank you!
