### ISSUE TITLE
How to reset driver/gpu

### ISSUE THREAD

**Issue by almson** [RadeonOpenCompute/ROCK-Kernel-Driver#11]
How can I reset the driver or GPU without rebooting the machine (which is very inconvenient for me)? 

A bad kernel has crashed my GPU. `vector_copy` sample hangs for 10 seconds then crashes with `Creating the queue failed`.

I tried `sudo rmmod amdgpu` and `sudo rmmod amdkfd`. 

```
"sudo rmmod amdgpu” terminated by signal SIGSEGV (Address boundary error)
"sudo rmmod amdkfd” terminated by signal SIGKILL (Forced quit)
```

after which `vector_copy` immediately reports `Getting a gpu agent failed.`

**Comment by gstoner** [comment]
I have the team look at how we can do a reset tool via the ROCm-SMI

greg
On Oct 3, 2016, at 6:05 PM, almson <notifications@github.com<mailto:notifications@github.com>> wrote:


How can I reset the driver or GPU without rebooting the machine (which is very inconvenient for me)?

A bad kernel has crashed my GPU. vector_copy sample hangs for 10 seconds then crashes with Creating the queue failed.

I tried sudo rmmod amdgpu and sudo rmmod amdkfd.

"sudo rmmod amdgpu” terminated by signal SIGSEGV (Address boundary error)
"sudo rmmod amdkfd” terminated by signal SIGKILL (Forced quit)


after which vector_copy immediately reports Getting a gpu agent failed.

**Comment by almson** [comment]
Thank you! Really looking forward to this because it's currently a big problem for me.

**Comment by arodrigx7** [comment]
Hey again,

We actually have this issue noted internally, and a fix should be coming out with ROCm 1.3.

If you are interested, this is the patch that introduced the regression:
https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/commit/d76d3c3ec7b27371855598d4ed281920a2e0c0cf

If you build with that patch reverted you should be able to rmmod/modprobe again.

Note that HW can get very tricky sometimes, and if there are some severe faults it is possible that other HW blocks are also in a bad state (MMUs, PCI bus, Memory corruption, etc). Reset in this fashion will probably work correctly in quite a few scenarios, so it is useful in dev environments. But it shouldn't be used outside those circumstances.

**Comment by almson** [comment]
Thank you very much. I will try to recompile without this commit.

**Comment by almson** [comment]
@arodrigx7 This hasn't really helped. `sudo rmmod amdkfd` now says `rmmod: ERROR: Module amdkfd is in use`. `sudo rmmod -f amdkfd` says `Resource temporarily unavailable`. `sudo rmmod amdgpu` still leads to `“sudo rmmod amdgpu” terminated by signal SIGSEGV (Address boundary error)`. No way to recover the GPU as far as I can see.

**Comment by almson** [comment]
@arodrigx7 I see that the patch deals with virtualized environments. Do you have documentation on how to use Fiji in a passthrough virtualized environment? Perhaps rebooting a VM is currently the best way of resetting the GPU?

**Comment by arodrigx7** [comment]
Hey,

Sorry about that. Seems like there might be another regression in the 1.2 branch that also interferes with rmmod/modprobe. This problem should be fixed in ROCm 1.3 which is coming soon. I'll make sure we add a test case for this to our CI server as well.

For future reference, you have the correct sequence of commands to accomplish this task. First rmmod amdgpu, then rmmod amdkfd.

Regarding virtualization. Running ROCm 1.2 in a virtualized environment is not something that we have validated. So I'm not super confident recommending this solution. If you do want to try it, you can use Alex Williamson's how to guide:
http://vfio.blogspot.ca/2015/05/vfio-gpu-how-to-series-part-1-hardware.html

It is pretty in-depth and goes over a lot of the details of setting a pic-passthrough environment using VFIO. Alex is one of the main maintainers for VFIO, so if you are interested in virtualization his blog has a lot of cool information. Make sure to use the VFIO based method, and not the pci-stub method.

Happy Canadian Thanksgiving btw, in case you are from around the area :)

**Comment by kentrussell** [comment]
We have support for GPU reset in the upcoming 1.9 branch, which could be worth a try!

**Comment by jlgreathouse** [comment]
To be more specific, the `gpu_recovery` mechanism that is [part of our GPU drivers now](https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/blob/roc-2.0.0/drivers/gpu/drm/amd/amdgpu/amdgpu_drv.c#L493) should handle the initial request in this issue. In particular, if you set the kernel driver parameter `amdgpu.gpu_recovery=1`, then [whenever there is a GPU timeout detected](https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/blob/roc-2.0.0/drivers/gpu/drm/amd/amdgpu/amdgpu_job.c#L31), it should automatically attempt to reset the GPU and bring it back up.

If you do not want to have these resets attempted automatically, or if your lockup is not being detected, you should be able to [use the debugfs mechanism](https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/blob/roc-2.0.0/drivers/gpu/drm/amd/amdgpu/amdgpu_fence.c#L717) to perform a manual GPU reset, even if you have not set the `gpu_recovery` parameter. To do this, (as root) read `/sys/kernel/debug/dri/N/amdgpu_gpu_recover`. `N` in this case is the number of the GPU you wish to reset in the DRI subsystem.

There hasn't been any other activity on this issue in a few years, and I just tested the `amdgpu_gpu_recover` mechanism on a few of my systems and found it to properly reset the GPU and allow it to work afterwards. As such, I'm going to close this one.
