### ISSUE TITLE
ROCK-Kernel-Driver build failing

### ISSUE THREAD

**Issue by gggh000** [RadeonOpenCompute/ROCK-Kernel-Driver#110]
build failed, see log in url. Can not paste as it is too big. 
https://u.pcloud.link/publink/show?code=XZPN7eXZLmcvTahxtFQMmLJBDANq8zePrsH7

**Comment by gggh000** [comment]
I am able to build vanilla kernel just fine: https://u.pcloud.link/publink/show?code=XZcJkeXZ0OOF8KbeyjfEwdEKBugpMbvQmf1y

**Comment by fxkamd** [comment]
Seems to be a general problem building this kernel version on your system. Probably nothing specific to our branch or our driver code.

make[4]: *** No rule to make target 'debian/canonical-certs.pem', needed by 'certs/x509_certificate_list'.  Stop.
make[4]: *** Waiting for unfinished jobs....

Does this help: https://askubuntu.com/questions/1329538/compiling-the-kernel-5-11-11

**Comment by gggh000** [comment]
I looked up there https://unix.stackexchange.com/questions/293642/attempting-to-compile-kernel-yields-a-certification-error
and found this was set on one of the system I was using:
CONFIG_SYSTEM_TRUSTED_KEYS="debian/canonical-certs.pem" 
once it is set to blank, build appears OK. It is not clear why i populated that field??
Both system (working / failing) was using fresh ubuntu1804 host).

**Comment by kentrussell** [comment]
Resolved by blanking out the trusted key. Not a kernel issue
