### ISSUE TITLE
Please add support rocm_smi_lib 4.5.0 to driver vega10

### ISSUE THREAD

**Issue by perestoronin** [RadeonOpenCompute/ROCK-Kernel-Driver#119]
https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/blob/5b46cf51a9b3166f6da30e2d4508d3ff48bce5de/drivers/gpu/drm/amd/pm/powerplay/hwmgr/vega10_hwmgr.c#L4738-L4751

Please  add support rocm_smi_lib 4.5.0 to driver vega10

https://github.com/RadeonOpenCompute/rocm_smi_lib/blob/98635ec03e9e3552a422a6442a9b251a7fa58643/src/rocm_smi.cc#L988-L1017

**Comment by kentrussell** [comment]
If the issue is with rocm_smi_lib, you should raise that in https://github.com/RadeonOpenCompute/rocm_smi_lib . Note that rocm_smi_lib just exposes what the HW can do via the kernel.
