### ISSUE TITLE
Question: 1.3 kernel version

### ISSUE THREAD

**Issue by Dekken** [RadeonOpenCompute/ROCK-Kernel-Driver#12]
Hey,

I've been having a lot of problems with this kernel, on both Ubuntu and Debian Jessie, can you tell me what kernel version the next release will be?

Also, can you tell me why I need a whole kernel at all? I like to use custom kernels for non-mainline schedulers and it really doesn't mix with that.

Cheers

**Comment by arodrigx7** [comment]
We have some modifications to the base kernel that have not yet been backported to regular distros, like changes to the base PCI subsystem. This makes releasing loadable kernel modules a non-trivial task.

However, 1.3 will be our first release with a supplementary DKMS package. The backwards compatibility isn't going to be full fledged, but running on new kernels should be OK.

To answer your other question, the 1.3 release will contain a 4.6 based kernel with a drm subsystem that is closer to 4.8 for the full kernel release.

Regards,
Andres




On Sat, Oct 22, 2016 at 5:11 PM -0400, " ♦♣♠♥" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey,

I've been having a lot of problems with this kernel, on both Ubuntu and Debian Jessie, can you tell me what kernel version the next release will be?

Also, can you tell me why I need a whole kernel at all? I like to use custom kernels for non-mainline schedulers and it really doesn't mix with that.

Cheers

**Comment by Dekken** [comment]
Cheers
