### ISSUE TITLE
How to build and install module for supporting CRIU

### ISSUE THREAD

**Issue by malixian** [RadeonOpenCompute/ROCK-Kernel-Driver#125]
I've learned that the criu-wip branch is already available, but I'm not sure how to replace my current ROCK. Can you provide me with some build and install commands for build this module? 
Thanks a lot.

**Comment by malixian** [comment]
@rajbhar can you give me some advice？

**Comment by kentrussell** [comment]
@fxkamd Would it be as simple as just running "make bindeb-pkg" (after copying in a valid kernel config) and doing a monolithic kernel installation? Did we test that workflow?

**Comment by rajbhar** [comment]
> @rajbhar can you give me some advice？
 
Hi, Our kernel patches have landed into https://gitlab.freedesktop.org/agd5f/linux now so please feel free to make a monolithic kernel build using make deb-pkg or whichever way you prefer.  fxkamd/criu-wip branch is obsolete now.

Also please use https://github.com/RadeonOpenCompute/criu/commits/amdgpu_rfc-211222 for user space as we are working on upstreaming our CRIU changes.

**Comment by rajbhar** [comment]
Hope it helps, closing it now.
