### ISSUE TITLE
Question about how to build ROCK in the form of modules

### ISSUE THREAD

**Issue by malixian** [RadeonOpenCompute/ROCK-Kernel-Driver#128]
I want to manually compile ROCK's kernel as a module, but I can't find any documentation on that.
You can see a few modules that ROCK need through the **lsmod | grep amdgpu** command. 

> amdgpu               5763072  1
> amd_iommu_v2           20480  1 amdgpu
> amd_sched              32768  1 amdgpu
> amdttm                 98304  1 amdgpu
> amdkcl                 24576  2 amdttm,amdgpu
> i2c_algo_bit           16384  2 ast,amdgpu
> drm_kms_helper        188416  5 ast,amdgpu,nvidia_drm
> drm                   491520  15 drm_kms_helper,amd_sched,amdttm,drm_vram_helper,ast,nvidia,amdgpu,nvidia_drm,ttm,amdkcl

How can I generate these modules by manual compilation? Thanks.

**Comment by fxkamd** [comment]
Normally you'd build an entire kernel that includes those modules.

The amdgpu-dkms package (formerly rock-dkms) included in our ROCm releasese packages only the source code of our modules and a bunch of scripts to configure and build them against supported Linux distribution kernels. This allows installation of updated kernel modules without replacing the entire kernel.

We don't currently publish the scripts used to build those DKMS packages.

**Comment by malixian** [comment]
Some wonder why these scripts are not published, it is very troublesome to use the entire kernel to debug.

**Comment by fxkamd** [comment]
I actually find it easier to debug with a whole kernel build. It allows me to enable various debug features. Incremental builds and module installations are also faster than building a DKMS package and then installing that.

The easiest way to debug a DKMS module is to edit the source code installed in /usr/src/amdgpu/... and then use the dkms command line to remove the old module and build the new one. On Debian or Ubuntu you can also use "dpkg-reconfigure amdgpu-dkms" as a short-cut.

**Comment by malixian** [comment]
> I actually find it easier to debug with a whole kernel build. It allows me to enable various debug features. Incremental builds and module installations are also faster than building a DKMS package and then installing that.
> 
> The easiest way to debug a DKMS module is to edit the source code installed in /usr/src/amdgpu/... and then use the dkms command line to remove the old module and build the new one. On Debian or Ubuntu you can also use "dpkg-reconfigure amdgpu-dkms" as a short-cut.

Thanks for your answer, got it.

**Comment by ccnankai** [comment]
@fxkamd   @malixian  
Hi, , I a beginner ,
If I compile the entire kernel, what steps are required?
Is **make menuconfig && make** two steps enough?    Are there any other steps？How to use the new compiled module file？
