### ISSUE TITLE
Build and Load(Unload) for 5.8.0-59-generic

### ISSUE THREAD

**Issue by hschoi4448** [RadeonOpenCompute/ROCK-Kernel-Driver#137]
Hello

I want to add some debug messages for the OpenCL kernel driver.
so, I build amdgpu.ko and tried to load but got an error like `kernel: poet: disagrees about version of symbol module_layout`.

1. How can I build `*.ko` for my Linux version 5.8.0-59-generic?
I can't find 5.8.0 release in https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/releases.  
currently I checkout `bcf876870b95592b52519ed4aafcf9d95999bc9c` and build. Is it the right way to do it? 
 
2. Is `-59-generic` LOCALVERSION? 

3. If the build is successful, how can I load the required modules?
 I'm using blacklist for unloading amdgpu because rmmod -f amdgpu not work. can I unload and Load without reboot server? 

4. I want to debug about `AMDKFD_IOC_WAIT_EVENTS`. but build make a lot of modules, how can I know which module to check?

**Comment by fxkamd** [comment]
If you download the package drivers, the kernel module will be built against your current kernel by DKMS. The module will be loaded automatically at boot. You can confirm the status with "lsmod" to see that amdgpu.ko is loaded, and "dkms status" to see whether the module was successfully built and installed for your kernel.

**Comment by fxkamd** [comment]
What's the problem with AMDKFD_IOC_WAIT_EVENTS? I just fixed a problem in this ioctl. See this patch: https://lore.kernel.org/all/20220804222901.134048-1-Felix.Kuehling@amd.com/

**Comment by hschoi4448** [comment]
> If you download the package drivers, the kernel module will be built against your current kernel by DKMS. The module will be loaded automatically at boot. You can confirm the status with "lsmod" to see that amdgpu.ko is loaded, and "dkms status" to see whether the module was successfully built and installed for your kernel.

Thanks for your comment. However, I have to manually build ROCK-Kernel-Driver for debugging purposes. And there are some issues with kernel module versions. How can I sovle the versions problem?

**Comment by fxkamd** [comment]
DKMS does exactly what you need. It compiles the kernel module from source on your system against your kernel headers. You can modify the source code in /usr/src/amdgpu/... and rebuild the module using the dkms command line.
