### ISSUE TITLE
R9 380 DVI-A recognized as DVI-D

### ISSUE THREAD

**Issue by YurumiBits** [RadeonOpenCompute/ROCK-Kernel-Driver#138]
I do have a R9 380 and i do have a VGA monitor connected using a DVI-A to vga adapter.
![immagine](https://user-images.githubusercontent.com/20691297/186905945-d73161e8-d427-48f3-b725-cea2aac45960.png)

 It works fine on windows but not in linux.
I notice that in xrandr show te DVI as DVI-D.
![immagine](https://user-images.githubusercontent.com/20691297/186905164-cae49685-24cd-474e-a600-4e257294bb18.png)

If i insert this in my boot.cfg
`amdgpu.dc=0 `
then the dvi-a outputs works but the other outputs like hdmi doesn't

**Comment by YurumiBits** [comment]
Ps. that's my machine
![immagine](https://user-images.githubusercontent.com/20691297/186906511-eb59db09-67a2-4f73-bbca-f0ba4225ba7c.png)

**Comment by kentrussell** [comment]
ROCm is primarily focused on compute, not graphics. For a graphics/display issue like that, you'll get a faster (and more useful) response by opening a bug report at https://bugzilla.kernel.org/enter_bug.cgi . Good luck!
