### ISSUE TITLE
roc-1.3.0 README

### ISSUE THREAD

**Issue by Dekken** [RadeonOpenCompute/ROCK-Kernel-Driver#14]
Shows "4.1 upstream"

Is this true?

**Comment by kentrussell** [comment]
That's a mistake, it should be 4.6. I'll fix that now

**Comment by Dekken** [comment]
Excellent, I'm going to try merge it with the [pk kernel](https://github.com/pfactum/pf-kernel/commits/pf-4.6) I'll let you know how I get on if you're interested.
