### ISSUE TITLE
platform for ROCM with PASID

### ISSUE THREAD

**Issue by xuehua** [RadeonOpenCompute/ROCK-Kernel-Driver#145]
Hi, 

I am looking for an APU that can run ROCM with ATS/PASIC support.  From the link below
https://www.tomshardware.com/news/amd-raven-ridge-apu-specifications,36375.html
It seems AMD Ryzen 5 2400G Processor with Radeon RX Vega 11 Graphics is raven ridge APU. Could you help to confirm whether this CPU support PASID? If not, could you recommend a specific CPU that can run ROCM with PASID support? 

Thanks a lot for your help.

**Comment by fxkamd** [comment]
Yes. I have one of those in my personal computer and experimented with it a few years ago. It should be supported with ATS/PASID by KFD. Unfortunately it's not supported by HIP AFAIK.

**Comment by creativechern** [comment]
Thanks a lot for the info. It's very helpful!
