### ISSUE TITLE
missing tagged release for rocm-dkms 5.4.5

### ISSUE THREAD

**Issue by BenWibking** [RadeonOpenCompute/ROCK-Kernel-Driver#148]
Hi,

There is a binary package for ROCm 5.4.5 that includes rocm-dkms 5.4.5, but there's no such tagged release here. Can you provide a tag for this version?

For this release, `rocm-smi --showdriverversion` shows driver version 5.18.13, which doesn't match `PACKAGE_VERSION` in drivers/gpu/drm/amd/dkms/config/config.h for any of the tagged releases.

**Comment by kentrussell** [comment]
The versioning for the amdgpu-dkms package is defined in dkms/configure.ac . From what I can tell, config.h represents the codebase used for the dkms code. This would be 5.18.0 for the 5.4 release. The value defined in configure.ac in the AC_INIT call is the true package version. This represents the code base (5.18) and the number of promotions done to mainline (13 in this case). 5.18.13 is considered to be the true version for that amdgpu-dkms package, as this is always incremented at each promotion. 

For my personal reference (I don't handle dkms versioning), where would you be seeing the PACKAGE_VERSION variable used? I can reach out to the dkms packaging guys if this is causing a discrepancy or a mismatch with userspace tools or package managers. Thanks!

**Comment by BenWibking** [comment]
Ah, ok. Thanks for clarifying. I don't see PACKAGE_VERSION used elsewhere, I had just missed the version number in configure.ac itself.
