### ISSUE TITLE
disabling compute cores

### ISSUE THREAD

**Issue by trinayan** [RadeonOpenCompute/ROCK-Kernel-Driver#19]
Hi,

I want to know if the driver provides some functionalities to turn off compute cores as required. I am doing some power studies and it would be good if this can be done. Thank you

**Comment by grmat** [comment]
amdgpu has that functionality. You have to pass it when loading the module

`modinfo amdgpu`
> `disable_cu:Disable CUs (se.sh.cu,...) (charp)`

**Comment by kentrussell** [comment]
Closing as resolved (kernel has functionality included since before 1.5, also over a year of inactivity on this issue)
