### ISSUE TITLE
kernel oops when running hip kernel with dev branch ROCR/ROCK

### ISSUE THREAD

**Issue by mattmacy** [RadeonOpenCompute/ROCK-Kernel-Driver#2]
When running the square.cpp sample I now see the following:

Mar 24 11:28:34 pandemonium kernel: [  639.895604] nvidia_uvm: Loaded the UVM driver, major device number 245
Mar 24 11:29:06 pandemonium kernel: [  671.693636] amdgpu: vram aperture is out of 40bit address base: 0x383fc0000000 limit 0x383fd0000000
Mar 24 11:29:06 pandemonium kernel: [  671.693749] amdgpu: vram aperture is out of 40bit address base: 0x383fe0000000 limit 0x383ff0000000
Mar 24 11:29:06 pandemonium kernel: [  671.696239] amdgpu: vram aperture is out of 40bit address base: 0x383fc0000000 limit 0x383fd0000000
Mar 24 11:29:06 pandemonium kernel: [  671.734321] amdgpu: vram aperture is out of 40bit address base: 0x383fe0000000 limit 0x383ff0000000
Mar 24 11:29:06 pandemonium kernel: [  671.776858] BUG: unable to handle kernel paging request at ffffc90019ecd000
Mar 24 11:29:06 pandemonium kernel: [  671.776863] IP: [<ffffffffc03e3dba>] set_trap_handler+0x1a/0x30 [amdkfd]
Mar 24 11:29:06 pandemonium kernel: [  671.776879] PGD ffec8f067 PUD ffeca0067 PMD fcf5f2067 PTE 0
Mar 24 11:29:06 pandemonium kernel: [  671.776883] Oops: 0002 [#1] SMP 
Mar 24 11:29:06 pandemonium kernel: [  671.776886] Modules linked in: nvidia_uvm(POE) vmw_vsock_vmci_transport vsock vmw_vmci rfcomm bnep binfmt_misc hid_logitech_hidpp btusb btbcm btintel bluetooth b43 mac80211 nls_iso8859_1 cfg80211 ssb intel_rapl iosf_mbi x86_pkg_temp_thermal eeepc_wmi intel_powerclamp coretemp asus_wmi sparse_keymap video mxm_wmi kvm crct10dif_pclmul crc32_pclmul ghash_clmulni_intel aesni_intel nvidia(POE) aes_x86_64 lrw gf128mul glue_helper ablk_helper cryptd serio_raw sb_edac edac_core snd_hda_codec_realtek snd_usb_audio snd_hda_codec_generic snd_usbmidi_lib snd_seq_midi hid_logitech_dj snd_seq_midi_event snd_hda_codec_hdmi snd_rawmidi snd_hda_intel snd_hda_controller snd_hda_codec snd_seq snd_hda_core snd_hwdep snd_seq_device bcma snd_pcm snd_timer snd mei_me lpc_ich soundcore mei shpchp wmi tpm_infineon mac_hid parport_pc ppdev lp parport autofs4 hid_generic usbhid hid amdkfd amd_iommu_v2 amdgpu psmouse amd_gnb_bus i2c_algo_bit e1000e ttm drm_kms_helper ahci ptp libahci drm pps_core
Mar 24 11:29:06 pandemonium kernel: [  671.776940] CPU: 0 PID: 4040 Comm: a.out Tainted: P           OE   4.1.0-201603162000-kfd-build-obsidian-82-generic #82
Mar 24 11:29:06 pandemonium kernel: [  671.776943] Hardware name: iXsystems CSE-COR-AIR540/RAMPAGE V EXTREME, BIOS 1902 12/18/2015
Mar 24 11:29:06 pandemonium kernel: [  671.776944] task: ffff880e71d93250 ti: ffff880ea4020000 task.ti: ffff880ea4020000
Mar 24 11:29:06 pandemonium kernel: [  671.776946] RIP: 0010:[<ffffffffc03e3dba>]  [<ffffffffc03e3dba>] set_trap_handler+0x1a/0x30 [amdkfd]
Mar 24 11:29:06 pandemonium kernel: [  671.776955] RSP: 0018:ffff880ea4023d48  EFLAGS: 00010286
Mar 24 11:29:06 pandemonium kernel: [  671.776956] RAX: ffffc90019ecd000 RBX: ffff880ff0f92e00 RCX: 0000000000000000
Mar 24 11:29:06 pandemonium kernel: [  671.776957] RDX: 0000000002400000 RSI: ffff880ff3251e20 RDI: ffff880ff0f92a00
Mar 24 11:29:06 pandemonium kernel: [  671.776959] RBP: ffff880ea4023d48 R08: ffff880ff0f92a00 R09: 0000000000000000
Mar 24 11:29:06 pandemonium kernel: [  671.776960] R10: ffff880f962af800 R11: 00007ffc39269e80 R12: ffff880ea4023dc0
Mar 24 11:29:06 pandemonium kernel: [  671.776961] R13: ffff880fb1275018 R14: ffff880fb1275000 R15: ffff880ea4023dc0
Mar 24 11:29:06 pandemonium kernel: [  671.776963] FS:  00007f8005ebc740(0000) GS:ffff880fff200000(0000) knlGS:0000000000000000
Mar 24 11:29:06 pandemonium kernel: [  671.776965] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Mar 24 11:29:06 pandemonium kernel: [  671.776966] CR2: ffffc90019ecd000 CR3: 0000000f3f50b000 CR4: 00000000001407f0
Mar 24 11:29:06 pandemonium kernel: [  671.776968] Stack:
Mar 24 11:29:06 pandemonium kernel: [  671.776969]  ffff880ea4023d78 ffffffffc03d8883 ffff880ea4023dc0 fffffffffffffff2
Mar 24 11:29:06 pandemonium kernel: [  671.776972]  000000000000001a 00000000fffffff2 ffff880ea4023e78 ffffffffc03d9ebf
Mar 24 11:29:06 pandemonium kernel: [  671.776975]  ffff880f962af800 ffffffffc03d8810 ffff880fb1275000 00007ffc39269e80
Mar 24 11:29:06 pandemonium kernel: [  671.776977] Call Trace:
Mar 24 11:29:06 pandemonium kernel: [  671.776986]  [<ffffffffc03d8883>] kfd_ioctl_set_trap_handler+0x73/0xc0 [amdkfd]
Mar 24 11:29:06 pandemonium kernel: [  671.776994]  [<ffffffffc03d9ebf>] kfd_ioctl+0x2bf/0x4d0 [amdkfd]
Mar 24 11:29:06 pandemonium kernel: [  671.777001]  [<ffffffffc03d8810>] ? kfd_ioctl_get_process_apertures+0x2e0/0x2e0 [amdkfd]
Mar 24 11:29:06 pandemonium kernel: [  671.777010]  [<ffffffff8106c240>] ? pte_alloc_one+0x30/0x50
Mar 24 11:29:06 pandemonium kernel: [  671.777015]  [<ffffffff811af63c>] ? __pte_alloc+0xcc/0x180
Mar 24 11:29:06 pandemonium kernel: [  671.777019]  [<ffffffff8120cd28>] do_vfs_ioctl+0x2f8/0x510
Mar 24 11:29:06 pandemonium kernel: [  671.777023]  [<ffffffff81066f76>] ? __do_page_fault+0x1b6/0x450
Mar 24 11:29:06 pandemonium kernel: [  671.777026]  [<ffffffff8120cfc1>] SyS_ioctl+0x81/0xa0
Mar 24 11:29:06 pandemonium kernel: [  671.777028]  [<ffffffff81067240>] ? do_page_fault+0x30/0x80
Mar 24 11:29:06 pandemonium kernel: [  671.777032]  [<ffffffff817d8132>] system_call_fastpath+0x16/0x75
Mar 24 11:29:06 pandemonium kernel: [  671.777034] Code: 00 0f 1f 44 00 00 55 31 c0 48 89 e5 5d c3 0f 1f 00 0f 1f 44 00 00 55 48 8b 46 f0 48 89 e5 8b 80 f4 01 00 00 48 03 86 e0 00 00 00 <48> 89 10 48 89 48 08 31 c0 5d c3 66 66 2e 0f 1f 84 00 00 00 00 
Mar 24 11:29:06 pandemonium kernel: [  671.777061] RIP  [<ffffffffc03e3dba>] set_trap_handler+0x1a/0x30 [amdkfd]
Mar 24 11:29:06 pandemonium kernel: [  671.777068]  RSP <ffff880ea4023d48>
Mar 24 11:29:06 pandemonium kernel: [  671.777069] CR2: ffffc90019ecd000
Mar 24 11:29:06 pandemonium kernel: [  671.777072] ---[ end trace 53807749a7eb2ed3 ]---

**Comment by jedwards-AMD** [comment]
This should be fixed with the new dev branch.

**Comment by mattmacy** [comment]
Working on the BSD port.  Assuming fixed.
