### ISSUE TITLE
linux-firmware rpm issue

### ISSUE THREAD

**Issue by oheid** [RadeonOpenCompute/ROCK-Kernel-Driver#21]
There seems to be a problem with the AMD HSA firmware package for Fedora (I did not check whether this also occurs in Ubuntu):
[http://packages.amd.com/rocm/yum/rpm/linux-firmware-201705121727-1.noarch.rpm](url) contains exclusively AMD related firmware, and is thus no replacement or update to the standard linux-firmware rpm (currently linux-firmware-20170313-72.git695f2d6d.fc25.noarch.rpm). Installing (or seemingly just updating) this package leaves the system devoid of any non-AMD firmware.
Due to file name collisions the two rpms cannot installed simultaneously either. There should be a single rpm with the latest firmware from both rpms.

**Comment by kentrussell** [comment]
This has been resolved in 1.8-and-later releases
