### ISSUE TITLE
Null pointer dereference in update_stream_scaling_settings

### ISSUE THREAD

**Issue by ernstp** [RadeonOpenCompute/ROCK-Kernel-Driver#23]
This isn't really compute related but it happened with the ROCK kernel so I thought it would be best to report it:

Jun 14 06:27:34 mammut kernel: [25320.162048] [drm] Atomic commit: SET crtc id 0: [ffff9c40b1acd000]
Jun 14 06:27:34 mammut kernel: [25320.162050] [drm] dc_commit_streams: 1 streams
Jun 14 06:27:34 mammut kernel: [25320.162052] [drm] core_stream 0x62476400: src: 0, 0, 3840, 2160; dst: 0, 0, 3840, 2160, colorSpace:1
Jun 14 06:27:34 mammut kernel: [25320.162053] [drm] 	pix_clk_khz: 533250, h_total: 4000, v_total: 2222, pixelencoder:1, displaycolorDepth:2
Jun 14 06:27:34 mammut kernel: [25320.162053] [drm] 	sink name: U24E850, serial: 810373974
Jun 14 06:27:34 mammut kernel: [25320.162054] [drm] 	link: 1
Jun 14 06:27:34 mammut kernel: [25320.162091] [drm] dce_get_required_clocks_state: clocks unsupported
Jun 14 06:27:34 mammut kernel: [25320.163545] [drm] Link: 1 eDP panel mode supported: 0 eDP panel mode enabled: 0 
Jun 14 06:27:34 mammut kernel: [25320.167649] [drm] [LKTN]	[DP][ConnIdx:1] HBR2x4 pass VS=1, PE=0^
Jun 14 06:27:34 mammut kernel: [25320.168288] [drm] [Mode]	[DP][ConnIdx:1] {3840x2160, 4000x2222@533250Khz}^
Jun 14 06:27:34 mammut kernel: [25320.179277] [drm] Atomic commit: SET crtc id 1: [ffff9c40b1ace000]
Jun 14 06:27:34 mammut kernel: [25320.179280] [drm] dc_commit_streams: 2 streams
Jun 14 06:27:34 mammut kernel: [25320.179281] [drm] core_stream 0x62476400: src: 0, 0, 3840, 2160; dst: 0, 0, 3840, 2160, colorSpace:1
Jun 14 06:27:34 mammut kernel: [25320.179282] [drm] 	pix_clk_khz: 533250, h_total: 4000, v_total: 2222, pixelencoder:1, displaycolorDepth:2
Jun 14 06:27:34 mammut kernel: [25320.179283] [drm] 	sink name: U24E850, serial: 810373974
Jun 14 06:27:34 mammut kernel: [25320.179283] [drm] 	link: 1
Jun 14 06:27:34 mammut kernel: [25320.179284] [drm] core_stream 0x2d771400: src: 0, 0, 3840, 2160; dst: 0, 0, 3840, 2160, colorSpace:1
Jun 14 06:27:34 mammut kernel: [25320.179285] [drm] 	pix_clk_khz: 533250, h_total: 4000, v_total: 2222, pixelencoder:1, displaycolorDepth:2
Jun 14 06:27:34 mammut kernel: [25320.179285] [drm] 	sink name: DELL P2415Q, serial: 808925260
Jun 14 06:27:34 mammut kernel: [25320.179285] [drm] 	link: 2
Jun 14 06:27:34 mammut kernel: [25320.179325] [drm] dce_get_required_clocks_state: clocks unsupported
Jun 14 06:27:34 mammut kernel: [25320.180762] [drm] Link: 2 eDP panel mode supported: 0 eDP panel mode enabled: 0 
Jun 14 06:27:34 mammut kernel: [25320.184879] [drm] [LKTN]	[DP][ConnIdx:2] HBR2x4 pass VS=1, PE=0^
Jun 14 06:27:34 mammut rtkit-daemon[1785]: Supervising 7 threads of 2 processes of 2 users.
Jun 14 06:27:34 mammut rtkit-daemon[1785]: Successfully made thread 3781 of process 2465 (n/a) owned by '1000' RT at priority 5.
Jun 14 06:27:34 mammut rtkit-daemon[1785]: Supervising 8 threads of 2 processes of 2 users.
Jun 14 06:27:34 mammut kernel: [25320.195473] [drm] GSL: Setting-up...
Jun 14 06:27:34 mammut kernel: [25320.195477] [drm] GSL: enabling trigger-reset
Jun 14 06:27:34 mammut kernel: [25320.195480] [drm] GSL: waiting for reset to occur.
Jun 14 06:27:34 mammut kernel: [25320.195505] [drm] GSL: reset occurred at wait count: 1
Jun 14 06:27:34 mammut kernel: [25320.195505] [drm] GSL: disabling trigger-reset.
Jun 14 06:27:34 mammut kernel: [25320.195507] [drm] GSL: Restoring register states.
Jun 14 06:27:34 mammut kernel: [25320.195509] [drm] GSL: Set-up complete.
Jun 14 06:27:34 mammut kernel: [25320.196985] [drm] [Mode]	[DP][ConnIdx:1] {3840x2160, 4000x2222@533250Khz}^
Jun 14 06:27:34 mammut kernel: [25320.196986] [drm] [Mode]	[DP][ConnIdx:2] {3840x2160, 4000x2222@533250Khz}^
Jun 14 06:27:34 mammut kernel: [25320.257333] [drm] link=2, dc_sink_in=          (null) is now Disconnected
Jun 14 06:27:34 mammut kernel: [25320.257334] [drm] DCHPD: connector_id=2: Old sink=ffff9c40b011ac00 New sink=          (null)
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): EDID vendor "SAM", prod id 3279
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Using hsync ranges from config file
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Using vrefresh ranges from config file
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Printing DDC gathered Modelines:
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Modeline "3840x2160"x0.0  533.25  3840 3888 3920 4000  2160 2163 2168 2222 +hsync -vsync (133.3 kHz eP)
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Modeline "1920x1080"x0.0  148.50  1920 2008 2052 2200  1080 1084 1089 1125 +hsync +vsync (67.5 kHz e)
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Modeline "2560x1440"x0.0  241.50  2560 2608 2640 2720  1440 1443 1448 1481 +hsync -vsync (88.8 kHz e)
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Modeline "800x600"x0.0   40.00  800 840 968 1056  600 601 605 628 +hsync +vsync (37.9 kHz e)
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Modeline "800x600"x0.0   36.00  800 824 896 1024  600 601 603 625 +hsync +vsync (35.2 kHz e)
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Modeline "640x480"x0.0   25.18  640 656 752 800  480 490 492 525 -hsync -vsync (31.5 kHz e)
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Modeline "1024x768"x0.0   65.00  1024 1048 1184 1344  768 771 777 806 -hsync -vsync (48.4 kHz e)
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Modeline "1280x800"x0.0   83.50  1280 1352 1480 1680  800 803 809 831 -hsync +vsync (49.7 kHz e)
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Modeline "1280x720"x59.9   74.50  1280 1344 1472 1664  720 723 728 748 -hsync +vsync (44.8 kHz e)
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Modeline "1280x1024"x0.0  108.00  1280 1328 1440 1688  1024 1025 1028 1066 +hsync +vsync (64.0 kHz e)
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Modeline "1600x900"x59.9  118.25  1600 1696 1856 2112  900 903 908 934 -hsync +vsync (56.0 kHz e)
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Modeline "1680x1050"x0.0  146.25  1680 1784 1960 2240  1050 1053 1059 1089 -hsync +vsync (65.3 kHz e)
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Modeline "1440x900"x0.0  106.50  1440 1520 1672 1904  900 903 909 934 -hsync +vsync (55.9 kHz e)
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Modeline "720x576"x0.0   27.00  720 732 796 864  576 581 586 625 -hsync -vsync (31.2 kHz e)
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): EDID vendor "SAM", prod id 3279
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Using hsync ranges from config file
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Using vrefresh ranges from config file
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Printing DDC gathered Modelines:
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Modeline "3840x2160"x0.0  533.25  3840 3888 3920 4000  2160 2163 2168 2222 +hsync -vsync (133.3 kHz eP)
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Modeline "1920x1080"x0.0  148.50  1920 2008 2052 2200  1080 1084 1089 1125 +hsync +vsync (67.5 kHz e)
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Modeline "2560x1440"x0.0  241.50  2560 2608 2640 2720  1440 1443 1448 1481 +hsync -vsync (88.8 kHz e)
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Modeline "800x600"x0.0   40.00  800 840 968 1056  600 601 605 628 +hsync +vsync (37.9 kHz e)
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Modeline "800x600"x0.0   36.00  800 824 896 1024  600 601 603 625 +hsync +vsync (35.2 kHz e)
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Modeline "640x480"x0.0   25.18  640 656 752 800  480 490 492 525 -hsync -vsync (31.5 kHz e)
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Modeline "1024x768"x0.0   65.00  1024 1048 1184 1344  768 771 777 806 -hsync -vsync (48.4 kHz e)
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Modeline "1280x800"x0.0   83.50  1280 1352 1480 1680  800 803 809 831 -hsync +vsync (49.7 kHz e)
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Modeline "1280x720"x59.9   74.50  1280 1344 1472 1664  720 723 728 748 -hsync +vsync (44.8 kHz e)
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Modeline "1280x1024"x0.0  108.00  1280 1328 1440 1688  1024 1025 1028 1066 +hsync +vsync (64.0 kHz e)
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Modeline "1600x900"x59.9  118.25  1600 1696 1856 2112  900 903 908 934 -hsync +vsync (56.0 kHz e)
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Modeline "1680x1050"x0.0  146.25  1680 1784 1960 2240  1050 1053 1059 1089 -hsync +vsync (65.3 kHz e)
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Modeline "1440x900"x0.0  106.50  1440 1520 1672 1904  900 903 909 934 -hsync +vsync (55.9 kHz e)
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Modeline "720x576"x0.0   27.00  720 732 796 864  576 581 586 625 -hsync -vsync (31.2 kHz e)
Jun 14 06:27:34 mammut kernel: [25320.262186] [drm] Atomic commit: RESET. crtc id 1:[ffff9c40b1ace000]
Jun 14 06:27:34 mammut kernel: [25320.262202] [drm] dc_commit_streams: 1 streams
Jun 14 06:27:34 mammut kernel: [25320.262204] [drm] core_stream 0x62476400: src: 0, 0, 3840, 2160; dst: 0, 0, 3840, 2160, colorSpace:1
Jun 14 06:27:34 mammut kernel: [25320.262204] [drm] 	pix_clk_khz: 533250, h_total: 4000, v_total: 2222, pixelencoder:1, displaycolorDepth:2
Jun 14 06:27:34 mammut kernel: [25320.262205] [drm] 	sink name: U24E850, serial: 810373974
Jun 14 06:27:34 mammut kernel: [25320.262205] [drm] 	link: 1
Jun 14 06:27:34 mammut kernel: [25320.269479] [drm] link=1, dc_sink_in=          (null) is now Disconnected
Jun 14 06:27:34 mammut kernel: [25320.269480] [drm] DCHPD: connector_id=1: Old sink=ffff9c40b0118c00 New sink=          (null)
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0): Allocate new frame buffer 3840x2160
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: (II) AMDGPU(0):  => pitch 15360 bytes
Jun 14 06:27:34 mammut kernel: [25320.312179] [drm] dce_get_required_clocks_state: clocks unsupported
Jun 14 06:27:34 mammut kernel: [25320.312200] [drm] [Mode]	[DP][ConnIdx:1] {3840x2160, 4000x2222@533250Khz}^
Jun 14 06:27:34 mammut kernel: [25320.312575] [drm] Atomic commit: RESET. crtc id 1:[ffff9c40b1ace000]
Jun 14 06:27:34 mammut kernel: [25320.314525] [drm] Atomic commit: RESET. crtc id 0:[ffff9c40b1acd000]
Jun 14 06:27:34 mammut kernel: [25320.314538] [drm] dc_commit_streams: 0 streams
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: New FB's refcnt was 0 in drmmode_fb_reference
Jun 14 06:27:34 mammut /usr/lib/gdm3/gdm-x-session[2118]: Old FB's refcnt was 0 in drmmode_fb_reference
Jun 14 06:27:34 mammut org.gnome.Shell.desktop[2445]: Window manager warning: Configuring CRTC 79 with mode 90 (3840 x 2160 @ 59,996624) at position 0, 0 and transform 0 failed
Jun 14 06:27:34 mammut kernel: [25320.362744] [drm:create_stream_for_sink [amdgpu]] *ERROR* Failed to create stream for sink!
Jun 14 06:27:34 mammut kernel: [25320.362792] [drm:create_stream_for_sink [amdgpu]] *ERROR* Failed to create stream for sink!
Jun 14 06:27:34 mammut kernel: [25320.362794] [drm] Atomic commit: SET crtc id 0: [ffff9c40b1acd000]
Jun 14 06:27:34 mammut kernel: [25320.362814] [drm:amdgpu_dm_atomic_commit_tail [amdgpu]] *ERROR* dm_dc_surface_commit: Failed to obtain stream on crtc (0)!
Jun 14 06:27:34 mammut kernel: [25320.362847] [drm:amdgpu_dm_atomic_commit_tail [amdgpu]] *ERROR* dm_dc_surface_commit: Failed to obtain stream on crtc (0)!
Jun 14 06:27:34 mammut kernel: [25320.363023] [drm:dc_stream_set_cursor_attributes [amdgpu]] *ERROR* DC: dc_stream is NULL!
Jun 14 06:27:34 mammut kernel: [25320.363043] [drm:dm_set_cursor [amdgpu]] *ERROR* DC failed to set cursor attributes
Jun 14 06:27:34 mammut kernel: [25320.363061] [drm:dc_stream_set_cursor_position [amdgpu]] *ERROR* DC: dc_stream is NULL!
Jun 14 06:27:34 mammut kernel: [25320.363079] [drm:dm_set_cursor [amdgpu]] *ERROR* DC failed to set cursor position
Jun 14 06:27:34 mammut kernel: [25320.363533] BUG: unable to handle kernel NULL pointer dereference at 0000000000000010
Jun 14 06:27:34 mammut kernel: [25320.363553] IP: [<ffffffffc05009c2>] update_stream_scaling_settings+0x42/0x190 [amdgpu]
Jun 14 06:27:34 mammut kernel: [25320.363589] PGD 0 
Jun 14 06:27:34 mammut kernel: [25320.363594] 
Jun 14 06:27:34 mammut kernel: [25320.363598] Oops: 0000 [#1] SMP
Jun 14 06:27:34 mammut kernel: [25320.363606] Modules linked in: binfmt_misc eeepc_wmi asus_wmi sparse_keymap video joydev input_leds kvm irqbypass crct10dif_pclmul crc32_pclmul snd_hda_codec_generic ghash_clmulni_intel aesni_intel aes_x86_64 lrw snd_hda_codec_hdmi gf128mul glue_helper ablk_helper cryptd snd_hda_intel snd_hda_codec snd_hda_core snd_hwdep snd_pcm_oss snd_mixer_oss snd_pcm serio_raw snd_seq_midi snd_seq_midi_event snd_rawmidi snd_seq snd_seq_device snd_timer snd soundcore ccp shpchp i2c_piix4 mac_hid i2c_designware_platform 8250_dw i2c_designware_core sbs sbshc max6650 parport_pc ppdev lp parport ip_tables x_tables autofs4 btrfs xor raid6_pq hid_generic usbhid hid amdkfd mxm_wmi amd_iommu_v2 amdgpu ttm drm_kms_helper syscopyarea sysfillrect sysimgblt psmouse fb_sys_fops igb drm dca ptp pps_core i2c_algo_bit ahci libahci
Jun 14 06:27:34 mammut kernel: [25320.363798]  gpio_amdpt wmi fjes gpio_generic
Jun 14 06:27:34 mammut kernel: [25320.363809] CPU: 0 PID: 2120 Comm: Xorg Not tainted 4.9.0-kfd+ #2
Jun 14 06:27:34 mammut kernel: [25320.363820] Hardware name: System manufacturer System Product Name/PRIME X370-PRO, BIOS 0803 06/05/2017
Jun 14 06:27:34 mammut kernel: [25320.363838] task: ffff9c4084a42ac0 task.stack: ffffaa4d08b98000
Jun 14 06:27:34 mammut kernel: [25320.363850] RIP: 0010:[<ffffffffc05009c2>]  [<ffffffffc05009c2>] update_stream_scaling_settings+0x42/0x190 [amdgpu]
Jun 14 06:27:34 mammut kernel: [25320.363888] RSP: 0018:ffffaa4d08b9baf8  EFLAGS: 00010286
Jun 14 06:27:34 mammut kernel: [25320.363898] RAX: 0000000000000000 RBX: ffff9c40b1acd000 RCX: 0000000000000000
Jun 14 06:27:34 mammut kernel: [25320.363912] RDX: 0000000000000000 RSI: ffff9c3ffe97fac0 RDI: ffff9c4064c95d00
Jun 14 06:27:34 mammut kernel: [25320.363925] RBP: ffffaa4d08b9bb28 R08: 0000000000000001 R09: ffff9c40af8a0000
Jun 14 06:27:34 mammut kernel: [25320.363939] R10: 0000000000000f00 R11: 0000000000000870 R12: ffff9c40b0109000
Jun 14 06:27:34 mammut kernel: [25320.363952] R13: ffff9c40b4e0dae0 R14: 0000000000000000 R15: ffff9c4064c95c00
Jun 14 06:27:34 mammut kernel: [25320.363966] FS:  00007fb60d1e7a40(0000) GS:ffff9c40be600000(0000) knlGS:0000000000000000
Jun 14 06:27:34 mammut kernel: [25320.363981] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Jun 14 06:27:34 mammut kernel: [25320.363992] CR2: 0000000000000010 CR3: 00000007c4978000 CR4: 00000000003406f0
Jun 14 06:27:34 mammut kernel: [25320.364006] Stack:
Jun 14 06:27:34 mammut kernel: [25320.364010]  ffffaa4d08b9bb28 0000000000000000 0000000000000000 ffff9c4000000000
Jun 14 06:27:34 mammut kernel: [25320.364027]  ffff9c4000000000 ffff9c40b1acd000 ffffaa4d08b9bc10 ffffffffc050390d
Jun 14 06:27:34 mammut kernel: [25320.364044]  0000000000000000 0000000000000000 0000000000000000 0000000000000000
Jun 14 06:27:34 mammut kernel: [25320.364061] Call Trace:
Jun 14 06:27:34 mammut kernel: [25320.364084]  [<ffffffffc050390d>] amdgpu_dm_atomic_commit_tail+0x66d/0xbe0 [amdgpu]
Jun 14 06:27:34 mammut kernel: [25320.364101]  [<ffffffffb01fac11>] ? kmem_cache_alloc_trace+0x181/0x190
Jun 14 06:27:34 mammut kernel: [25320.364117]  [<ffffffffc03cadb7>] ? drm_atomic_helper_setup_commit+0x2f7/0x340 [drm_kms_helper]
Jun 14 06:27:34 mammut kernel: [25320.364136]  [<ffffffffc03caeb6>] ? drm_atomic_helper_wait_for_dependencies+0xb6/0x180 [drm_kms_helper]
Jun 14 06:27:34 mammut kernel: [25320.364157]  [<ffffffffc03cb28e>] commit_tail+0x3e/0x60 [drm_kms_helper]
Jun 14 06:27:34 mammut kernel: [25320.364172]  [<ffffffffc03cb36c>] drm_atomic_helper_commit+0x9c/0xe0 [drm_kms_helper]
Jun 14 06:27:34 mammut kernel: [25320.364193]  [<ffffffffc02e7419>] drm_atomic_commit+0x49/0x50 [drm]
Jun 14 06:27:34 mammut kernel: [25320.364208]  [<ffffffffc03c8bc7>] drm_atomic_helper_connector_set_property+0x87/0xc0 [drm_kms_helper]
Jun 14 06:27:34 mammut kernel: [25320.364231]  [<ffffffffc02eb10c>] drm_mode_connector_set_obj_prop+0x3c/0x70 [drm]
Jun 14 06:27:34 mammut kernel: [25320.364250]  [<ffffffffc02ec48c>] drm_mode_obj_set_property_ioctl+0xfc/0x140 [drm]
Jun 14 06:27:34 mammut kernel: [25320.364269]  [<ffffffffc02eb170>] drm_mode_connector_property_set_ioctl+0x30/0x40 [drm]
Jun 14 06:27:34 mammut kernel: [25320.364289]  [<ffffffffc02d2d99>] drm_ioctl+0x1f9/0x480 [drm]
Jun 14 06:27:34 mammut kernel: [25320.364305]  [<ffffffffc02eb140>] ? drm_mode_connector_set_obj_prop+0x70/0x70 [drm]
Jun 14 06:27:34 mammut kernel: [25320.364321]  [<ffffffffb0269670>] ? ep_ptable_queue_proc+0xa0/0xa0
Jun 14 06:27:34 mammut kernel: [25320.364346]  [<ffffffffc041c04f>] amdgpu_drm_ioctl+0x4f/0x90 [amdgpu]
Jun 14 06:27:34 mammut kernel: [25320.364359]  [<ffffffffb0235aa4>] do_vfs_ioctl+0x94/0x5c0
Jun 14 06:27:34 mammut kernel: [25320.364371]  [<ffffffffb0708fb2>] ? __sys_recvmsg+0x62/0x80
Jun 14 06:27:34 mammut kernel: [25320.364383]  [<ffffffffb0236049>] SyS_ioctl+0x79/0x90
Jun 14 06:27:34 mammut kernel: [25320.364394]  [<ffffffffb083807b>] entry_SYSCALL_64_fastpath+0x1e/0xad
Jun 14 06:27:34 mammut kernel: [25320.364407] Code: 00 48 c7 44 24 08 00 00 00 00 48 c7 44 24 10 00 00 00 00 4c 8b 48 28 0f 84 d1 00 00 00 8b 46 20 44 8b 57 5c 48 89 d1 44 8b 5f 70 <44> 8b 42 10 8b 7a 28 83 f8 03 44 89 54 24 10 44 89 5c 24 14 44 
Jun 14 06:27:34 mammut kernel: [25320.364487] RIP  [<ffffffffc05009c2>] update_stream_scaling_settings+0x42/0x190 [amdgpu]
Jun 14 06:27:34 mammut kernel: [25320.364520]  RSP <ffffaa4d08b9baf8>
Jun 14 06:27:34 mammut kernel: [25320.364527] CR2: 0000000000000010
Jun 14 06:27:34 mammut kernel: [25320.383596] ---[ end trace 395a6a2c42173531 ]---
Jun 14 06:27:35 mammut kernel: [25321.188572] [drm] [Detect]	[DP][ConnIdx:2] Rx Caps: 12 14 C4 01 01 00 01 82 02 02 06 00 00 00 00 ^
Jun 14 06:27:35 mammut kernel: [25321.196036] [drm] [LKTN]	[DP][ConnIdx:2] HBR2x4 pass VS=2, PE=1^
Jun 14 06:27:35 mammut kernel: [25321.207215] [drm] [Detect]	[DP][ConnIdx:2] DELL P2415Q: [Block 0] 00 FF FF FF FF FF FF 00 10 AC BE A0 4C 38 37 30 02 19 01 04 B5 35 1E 78 3A E2 45 A8 55 4D A3 26 0B 50 54 A5 4B 00 71 4F 81 80 A9 C0 A9 40 D1 C0 E1 00 D1 00 01 01 4D D0 00 A0 F0 70 3E 80 3E 30 35 00 0F 28 21 00 00 1A 00 00 00 FF 00 50 32 50 43 32 35 31 35 30 37 38 4C 0A 00 00 00 FC 00 44 45 4C 4C 20 50 32 34 31 35 51 0A 20 00 00 00 FD 00 1D 4C 1E 8C 36 00 0A 20 20 20 20 20 20 01 4B ^
Jun 14 06:27:35 mammut kernel: [25321.207224] [drm] [Detect]	[DP][ConnIdx:2] DELL P2415Q: [Block 1] 02 03 1D F1 50 90 05 04 02 07 16 01 14 1F 12 13 20 21 22 03 06 23 09 07 07 83 01 00 00 02 3A 80 18 71 38 2D 40 58 2C 25 00 0F 28 21 00 00 1E 01 1D 80 18 71 1C 16 20 58 2C 25 00 0F 28 21 00 00 9E 56 5E 00 A0 A0 A0 29 50 30 20 35 00 0F 28 21 00 00 1A 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 3D ^
Jun 14 06:27:35 mammut kernel: [25321.207226] [drm] dc_link_detect: manufacturer_id = AC10, product_id = A0BE, serial_number = 3037384C, manufacture_week = 2, manufacture_year = 25, display_name = DELL P2415Q, speaker_flag = 1, audio_mode_count = 1
Jun 14 06:27:35 mammut kernel: [25321.207228] [drm] dc_link_detect: mode number = 0, format_code = 1, channel_count = 1, sample_rate = 7, sample_size = 7
Jun 14 06:27:35 mammut kernel: [25321.207229] [drm] link=2, dc_sink_in=ffff9c4064c90400 is now Connected
Jun 14 06:27:35 mammut kernel: [25321.207230] [drm] DCHPD: connector_id=2: Old sink=          (null) New sink=ffff9c4064c90400
Jun 14 06:27:35 mammut kernel: [25321.568020] [drm] [Detect]	[DP][ConnIdx:1] Rx Caps: 12 14 C4 01 01 00 01 C0 02 02 06 00 00 00 00 ^
Jun 14 06:27:35 mammut kernel: [25321.575465] [drm] [LKTN]	[DP][ConnIdx:1] HBR2x4 pass VS=2, PE=1^
Jun 14 06:27:35 mammut kernel: [25321.586328] [drm] [Detect]	[DP][ConnIdx:1] U24E850: [Block 0] 00 FF FF FF FF FF FF 00 4C 2D CF 0C 56 53 4D 30 16 19 01 04 A5 34 1D 78 3B 12 55 A9 54 4D 9F 25 0C 50 54 23 08 00 81 00 81 C0 81 80 A9 C0 B3 00 95 00 01 01 01 01 4D D0 00 A0 F0 70 3E 80 30 20 35 00 09 25 21 00 00 1A 00 00 00 FD 00 28 3C 87 87 3C 01 0A 20 20 20 20 20 20 00 00 00 FC 00 55 32 34 45 38 35 30 0A 20 20 20 20 20 00 00 00 FF 00 48 54 48 47 35 30 30 32 35 32 0A 20 20 01 C2 ^
Jun 14 06:27:35 mammut kernel: [25321.586337] [drm] [Detect]	[DP][ConnIdx:1] U24E850: [Block 1] 02 03 0E F0 41 10 23 09 07 07 83 01 00 00 02 3A 80 18 71 38 2D 40 58 2C 45 00 09 25 21 00 00 1E 56 5E 00 A0 A0 A0 29 50 30 20 35 00 09 25 21 00 00 1A 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 D3 ^
Jun 14 06:27:35 mammut kernel: [25321.586339] [drm] dc_link_detect: manufacturer_id = 2D4C, product_id = CCF, serial_number = 304D5356, manufacture_week = 22, manufacture_year = 25, display_name = U24E850, speaker_flag = 1, audio_mode_count = 1
Jun 14 06:27:35 mammut kernel: [25321.586340] [drm] dc_link_detect: mode number = 0, format_code = 1, channel_count = 1, sample_rate = 7, sample_size = 7
Jun 14 06:27:35 mammut kernel: [25321.586341] [drm] link=1, dc_sink_in=ffff9c4064c93400 is now Connected
Jun 14 06:27:35 mammut kernel: [25321.586342] [drm] DCHPD: connector_id=1: Old sink=          (null) New sink=ffff9c4064c93400
Jun 14 06:27:37 mammut kernel: [25323.207791] [drm] amdgpu_dm_irq_schedule_work FAILED src 4
Jun 14 06:27:42 mammut kernel: [25328.829002] [drm] amdgpu_dm_irq_schedule_work FAILED src 4
Jun 14 06:27:43 mammut kernel: [25329.847442] [drm] amdgpu_dm_irq_schedule_work FAILED src 4
Jun 14 06:27:49 mammut kernel: [25335.083962] [drm] amdgpu_dm_irq_schedule_work FAILED src 4
Jun 14 06:27:50 mammut kernel: [25336.097016] [drm] amdgpu_dm_irq_schedule_work FAILED src 4
Jun 14 06:27:55 mammut kernel: [25341.327560] [drm] amdgpu_dm_irq_schedule_work FAILED src 4
Jun 14 06:27:56 mammut kernel: [25342.347293] [drm] amdgpu_dm_irq_schedule_work FAILED src 4
Jun 14 06:28:01 mammut kernel: [25347.580611] [drm] amdgpu_dm_irq_schedule_work FAILED src 4
Jun 14 06:28:02 mammut kernel: [25348.597300] [drm] amdgpu_dm_irq_schedule_work FAILED src 4
Jun 14 06:28:07 mammut kernel: [25353.835894] [drm] amdgpu_dm_irq_schedule_work FAILED src 4
Jun 14 06:28:08 mammut kernel: [25354.856766] [drm] amdgpu_dm_irq_schedule_work FAILED src 4
Jun 14 06:28:14 mammut kernel: [25360.099215] [drm] amdgpu_dm_irq_schedule_work FAILED src 4
Jun 14 06:28:15 mammut kernel: [25361.116691] [drm] amdgpu_dm_irq_schedule_work FAILED src 4
Jun 14 06:28:20 mammut kernel: [25366.342524] [drm] amdgpu_dm_irq_schedule_work FAILED src 4
Jun 14 06:28:21 mammut kernel: [25367.356617] [drm] amdgpu_dm_irq_schedule_work FAILED src 4
Jun 14 06:28:26 mammut kernel: [25372.595842] [drm] amdgpu_dm_irq_schedule_work FAILED src 4
Jun 14 06:28:27 mammut kernel: [25373.616542] [drm] amdgpu_dm_irq_schedule_work FAILED src 4

**Comment by kentrussell** [comment]
Can you try the 1.9 release and see if the issue persists? And is the issue only on 1.9, or is it found on the upstream amdgpu branch as well?

**Comment by jlgreathouse** [comment]
With 2.0 released and no response since the release of 1.9, I'm going to be optimistic here and assume this is fixed. :)
