### ISSUE TITLE
ROC without IOMMU

### ISSUE THREAD

**Issue by insujang** [RadeonOpenCompute/ROCK-Kernel-Driver#25]
Is it possible to use ROC without using amd_iommu_v2?

In the current implementation, amdkfd depends on amd_iommu_v2 kernel module, which is for IOMMU. Due to this dependency, I cannot use ROC in a KVM virtual machine, as QEMU doesn't support both IOMMU emulation and VFIO-passthrough at the same time.

Is it possible to use the framework without iommu module functionality?

Thanks.

**Comment by johnbridgman** [comment]
It is required for APUs since the current implementation uses IOMMUv2 to provide CPU/GPU pointer equivalency across the entire user process address space and allow GPU access to unpinned memory. It should not be required for dGPUs though.

What hardware are you running ?

**Comment by insujang** [comment]
@johnbridgman Thank you for your quick reply!

I'm not using APU. My machine setup is as follows.

CPU: Intel Core i7 6700
GPU: AMD Radeon RX 480

Then does it mean in my machine it would work without IOMMUv2?

**Comment by johnbridgman** [comment]
Yes, that is my understanding. I don't think your CPU exposes IOMMUv2 functionality to the PCIE bus anyways, even without virtualization.

**Comment by insujang** [comment]
@johnbridgman 
Yes, I agree that Intel CPUs do not support AMD IOMMU. But when I run it on my host machine, AMD IOMMUv2 is initialized with no problem and I could successfully run the sample.

However, In the guest machine, the kernel module says
`AMD IOMMUv2 functionality not available on this system`
and no gpu agent is added to the ROC topology. So when I run the sample,
`Getting a gpu agent failed: 1000.`
is printed. 
So that's why I thought this kernel module is the problem.

Then what would be a problem? I willingly give any information that you request to solve this problem.

Current system setup:
Using Core i7 6700 and AMD Radeon RX 480 hardware
Host: Ubuntu 16.04.2 LTS with kernel version 4.11. Qemu 2.7.92
Guest: Ubuntu 16.04.2 LTS with kernel version 4.9 (latest version of this repo) + ROCT + ROCR 1.6, vfio-passthrough is used to pass Radeon RX 480 through to the guest machine.

There is no log in `dmesg` from amdkfd module, and following messages from amd_iommu_v2 module
```
[7.260252] AMD IOMMUv2 driver by Joerg Roedel <jroedel@suse.de>
[7.260256] AMD IOMMUv2 functionality not available on this system
```

Thanks!

**Comment by johnbridgman** [comment]
When you say "kernel version 4.9 (latest version of this repo)" are you referring to the 4.9 kernel from the ROCK repo or something else ?

**Comment by insujang** [comment]
@johnbridgman 
I meant the first one: 4.9 kernel from the ROCK repo.

Thank you for your help! Let me keep trying and leave more comments about it. Thanks!

**Comment by insujang** [comment]
Removing amd_iommu_v2 module from the kernel and changing the module loading order (amdkfd->amdgpu), amdkfd prints the meaningful message:
```
kfd kfd: skipped device 1002:67df, PCI rejects atomics
```

which means emulated PCIe does not support PCIe 3.0 atomic extension, which also replied in [ROCR repo](https://github.com/RadeonOpenCompute/ROCR-Runtime/issues/23)..
I should find a way to enable in QEMU vm.

Thank you!
