### ISSUE TITLE
Gigabyte AM4 bug in kernel

### ISSUE THREAD

**Issue by ratbuddy** [RadeonOpenCompute/ROCK-Kernel-Driver#27]
I'm hitting same bug as reported here https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1671360/+index?comments=all on my Gigabyte AM4 board - can that fix please be backported in?

Edit: Sorry, I realize this might be the wrong place to post this one, I'll look around for a better place, but it's happening trying to boot the rocm 1.6-77 kernel..

**Comment by fxkamd** [comment]
Yes, our internal test team also ran into this problem. We've backported the fix and it will be in the next release.

**Comment by ratbuddy** [comment]
That's great, thanks. Is there a way I could install the fix early? My Vega FE is idle :(

**Comment by fxkamd** [comment]
Not sure it this is the answer you wanted to hear, but nothing stops you from backporting the patches to the ROCK kernel source and compiling it yourself.

**Comment by ratbuddy** [comment]
I was thinking more like an advanced/test copy of the upcoming release, I'm not familiar enough to backport it myself. Thanks anyway!

**Comment by fxkamd** [comment]
The next release should be a minor 1.6.1 update with bug fixes. It should only be a few days away.
