### ISSUE TITLE
GPU Error 147 - Running ROCM Kernel 4.11.0-kfd-compute-rocm-rel-1.6-148

### ISSUE THREAD

**Issue by daxgames** [RadeonOpenCompute/ROCK-Kernel-Driver#31]
I am running a crypto currency miner with 6 - AMD RX480 and I have the errors below CONTINUOUSLY on the console when running the kernel in the subject.  The errors cause degraded hashing performance on one card.  If I remove that card no errors.  I have tried different cards and different slots all have the same issues with the mentioned kernel.  I also have had amdgpupro 17.10 and 17.30 on the system, same results with both with the mentioned kernel.  Other ubuntu 16.04 kernels work fine.

See photo:
![gpu_error_147](https://user-images.githubusercontent.com/7318053/30509386-06178fdc-9a75-11e7-83f6-ab0b28e6a8e6.JPG)

**Comment by gstoner** [comment]
On a particular PCIe slot where your run 6 GPU on PLX switch or some other  PCIe breakout switch  I guess,  you have GPU 147 error. 

- What CPU, are you running the GPU as PCIe Gen3 1x lanes ?  Or are you running PCIe Gen 2 lanes 
- Does it always fail on the same slot?
- So it is  failing with the same GPU 147 error for 4.11-148 ROCm driver and for  17.10 and 17.30

But if you run stock 16.04 kernel with unknown driver config it works

**Comment by daxgames** [comment]
Gen2, it is always GPU5.  GPUs are 0-5, I do not believe it is a particular slot but I think it is because it is the 6th GPU.  I verified this by using a 1x-3x PCie expansion board and plugging 2 cards into it and had the same issues in multiple motherboard slots.

I just duplicated the issue running 4.4.0-93-generic and amd-gpupro17.30 so maybe its 17.30 and not the ROCm.

To be clear if I am using ROCm do I need amd-gpupro installed at all?  The docs are a little sparse.

**Comment by daxgames** [comment]
Currently I am running all 6 cards into 6 motherboard slots using PCIe->usb->PCIe-1x adapters.

**Comment by gstoner** [comment]
Ok problem one ROCm uses Atomic Completer for Signaling which is only supported PCIe gen 3 Lanes on Haswell or newer CPU PCIe Root I/O complex.    ROCm stack is not supposed to be mixed with AMDGPUpro stack.    The. ROCm stack is not to be overlain on the AMDGPUpro drivers 

ROCm 1.6.3 Ubuntu  driver has dependencies on. KFD in Linux Kernel 4.11 we ship. 

Did you read any of these documents prior to installing. 

- https://rocm.github.io/install.html
- https://rocm.github.io/ROCmInstall.html 
- https://rocm.github.io/install_issues.html
- http://rocm-documentation.readthedocs.io/en/latest/Installation_Guide/Installation-Guide.html

**Comment by daxgames** [comment]
Before installing  - No, after while troubleshooting yes, some of them.  A friend simply gave me the below.

wget -qO - http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key | sudo apt-key add -
sudo sh -c 'echo deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ xenial main > /etc/apt/sources.list.d/rocm.list'
sudo apt-get remove rocm-smi
sudo apt-get update
sudo apt-get install rocm
#edit grub
sudo nano  /etc/default/grub
#2MB fragments for Ellesmere are enabled with a grub option:
GRUB_CMDLINE_LINUX="amdgpu.vm_fragment_size=9"
sudo update-grub 
sudo reboot

I did the above on a working miner that already had amd-gpupro 17,10 on it and immediately saw the issue I described.

I will try and go back and follow you instructions and post back here the results.

**Comment by daxgames** [comment]
@gstoner - are you suggesting my hardware config does not support ROCm or the fact I installed it over amd-gpupro?  Just wanting to clarify, the Monerboard I have is for mining.

**Comment by gstoner** [comment]
What you're doing is an unsupported configuration,  ROCm has its own base driver is installed with the package,   We use PCIe Atomics for Signalling.   How you configured it will cause stability issues.

**Comment by gstoner** [comment]
Check if IOMMU  on Intel is turned on shut if off.

**Comment by fxkamd** [comment]
VMID 6 is not a ROCm context. This is either graphics or ORCA-based OpenCL.
