### ISSUE TITLE
Update README.md to explain the diff with 4.15rc2

### ISSUE THREAD

**Issue by alexanderkjeldaas** [RadeonOpenCompute/ROCK-Kernel-Driver#37]
Hi,

Now with the latest 4.15rc2 updates, it's a bit confusing to understand how to use ROCm.  What is required to get OpenCL working with 4.15rc2 for example?

What is the kfd situation currently?
There are comments in `README.md` saying things like "not in upstream".  These should be changed into "not in upstream as of <version>" because when I see that the README was updated in August I know that this is probably untrue, and if the information can't be trusted then it loses value.

**Comment by gstoner** [comment]
The team is still upstreaming more of the bits needed to DGPU, we will make an announcement when this is done.

**Comment by fxkamd** [comment]
Upstreaming is still in progress. The changes in 4.15 provide some improvements for CZ and KV, but do not add support for dGPUs yet. The KFD ioctl API in 4.15 is different from the ROCm releases. So the user mode components from current ROCm releases will not work on upstream KFD yet.

Once upstreaming is more or less complete, a future ROCm release will update the KFD ioctl API to match upstream so that ROCm user mode can run on an upstream kernel.

**Comment by paulmenzel** [comment]
Thank you for the update. Is there a roadmap though? Making plans and tests to switch away from CUDA the current situation doesn’t look to promissing to convince others.

**Comment by paulmenzel** [comment]
For example, where is the current development branch, which is compatible with Linux master?

**Comment by gstoner** [comment]
I am confused by your comment since we seen strong community building up go here rocm.github.io for documentation,  what your talking about is a desire to build an entire stack from the source.   You need to understand we are currently north 26 packages.   On Roadmap we are looking at what we can publish, now we passed getting the base in place.  

What is critical to moving away from CUDA is more than kernel driver,  but all the key libraries, needed for software development, here you see we were very aggressive to fill in the key gaps.    When we publish roadmap it will be at rocm.github.io,   Documentation is already being built out at http://rocm-documentation.readthedocs.io/en/latest/index.html.    We have been very small team building this out, but are growing in 2018 so we can fill in the key gap.    

What we need are people like you to help us take this to next level by doing contribution where you best,  then you have the product you want.

**Comment by paulmenzel** [comment]
Am 03.02.2018 um 18:53 schrieb Gregory Stoner:
> I am confused by your comment since we seen strong community building
> up go here rocm.github.io for documentation,  what your talking about
> is a desire to build an entire stack from the source.   You need to
> understand we are currently north 26 packages.   On Roadmap we are
> looking at what we can publish, now we passed getting the base in
> place.

I am glad to hear that, but for me the first impression is, that it’s
not useable yet for us in the current state. Being able to built against 
the latest Linux kernel is a strong requirement for us, and that’s also 
what you should do if you plan on getting it upstreamed. (But I guess 
you know that.)

> What is critical to moving away from CUDA is more than kernel driver,
> but all the key libraries, needed for software development, here you
> see we were very aggressive to fill in the key gaps.    When we
> publish roadmap it will be at rocm.github.io,   Documentation is
> already being built out at
> http://rocm-documentation.readthedocs.io/en/latest/index.html.    We
> have been very small team building this out, but are growing in 2018
> so we can fill in the key gap.

I am unwilling to pull the Web site every now, and then, just to see if 
a roadmap was published or not. A mailing list would be great, where I 
could subscribe to keep mysef up-to-date.

> What we need are people like you to help us take this to next level
> by doing contribution where you best,  then you have the product you
> want.

I understand, that this is what you hope for. But currently, my 
colleagues and I have no time to work on these besides reporting issues 
we face. If there was a roadmap or issues that need to be resolved with 
corresponding numbers for work hours, I could talk to people to maybe 
get involved, but in the current form that’s not possible. This issues 
is also off-topic for this discussion. What is the correct forum to 
discuss these things?

**Comment by fxkamd** [comment]
Hi Paul,

The upstreaming is an ongoing effort. Basically, it happens as fast as I can get the patches cleaned up, submitted for upstream code review, and approved by the maintainer Oded. Once Oded accepts the patches into his tree, they go to Dave Airlie, the maintainer of the DRM subsystem, and from there to Linus Torvalds and the official kernel master branch. There is one release cycle lag between Dave Airlie and Linus Torvalds. Therefore, patches accepted by Oded before the 4.16 release will only appear in Linux master in 4.17, for example.

The review of the patches happens on amd-gfx@lists.freedesktop.org. Phoronix is also reporting about the progress. The latest status update on Phoronix is this AFAIK: https://www.phoronix.com/scan.php?page=news_item&px=Vega-Mainline-Compute-State

It's hard to predict exactly how long the upstreaming is going to take. My estimates have been consistently wrong, and I am very careful about making more predictions. Currently it looks like GFXv8 dGPU support should make it into 4.17. Support for GFXv9 will probably not make it into 4.17 yet.

I periodically publish my WIP on GitHub in both the Kernel and Thunk repositories:
https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/tree/fkxamd/drm-next-wip
https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/tree/fxkamd/drm-next-wip

Hope this helps.

**Comment by paulmenzel** [comment]
Am 05.02.2018 um 18:17 schrieb Felix Kuehling:

> The upstreaming is an ongoing effort. Basically, it happens as fast
> as I can get the patches cleaned up, submitted for upstream code
> review, and approved by the maintainer Oded. Once Oded accepts the
> patches into his tree, they go to Dave Airlie, the maintainer of the
> DRM subsystem, and from there to Linus Torvalds and the official
> kernel master branch. There is one release cycle lag between Dave
> Airlie and Linus Torvalds. Therefore, patches accepted by Oded before
> the 4.16 release will only appear in Linux master in 4.17, for
> example.

Yes, I know that development process.

> The review of the patches happens on amd-gfx@lists.freedesktop.org.
> Phoronix is also reporting about the progress. The latest status
> update on Phoronix is this AFAIK:
> https://www.phoronix.com/scan.php?page=news_item&px=Vega-Mainline-Compute-State
>
> It's hard to predict exactly how long the upstreaming is going to
> take. My estimates have been consistently wrong, and I am very
> careful about making more predictions. Currently it looks like GFXv8
> dGPU support should make it into 4.17. Support for GFXv9 will
> probably not make it into 4.17 yet.

Understood. There should be one place there, where this informationen is 
available. I’ll subscribe to amd-gfx, but it looks like an announcement 
list of some kind would be nice to have.

> I periodically publish my WIP on GitHub in both the Kernel and Thunk
> repositories: 
> https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/tree/fkxamd/drm-next-wip
>
> https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/tree/fxkamd/drm-next-wip >
> Hope this helps.

Yes, that helped quite a lot. Especially telling the branches I can use 
with recent Linux kernel.

**Comment by alecuba16** [comment]
@fxkamd Do you have the commits for the 4.15.7?  Or what base kernel you got for 4.16-rc1 

Sin I have downloaded the current 4.16-rc1 from kernel.org and compared with MELD to see the differences but there are many different things that have nothing in common with AMD drivers. Please, can you tell me the base kernel that you got before changes/inject of the drivers in order to do the same for my kernel 4.15.7? thanks!!

**Comment by fxkamd** [comment]
My tree is based on git://people.freedesktop.org/~gabbayo/linux, branch amdkfd-next. However that's a moving target too so you may find that the current version of that branch doesn't match what my tree is based on any more.

**Comment by oscarbg** [comment]
@fxkamd Some update on upstream support on Vega GPUs? Efforts to make it happen into 4.18, underway? hope once 4.17rc1 gets released next month with up to Polaris support patches/kernel branches start appearing with Vega support..
Thanks.

**Comment by fxkamd** [comment]
I sent out a patch series for Vega10 support about a week ago. It's currently waiting for review. The maintainer has been on vacation for a while but should be back next week.

**Comment by justxi** [comment]
Does the mainline kernel (kernel.org) 4.17-rc3 already contain support for Polaris based GPUs (Radeon RX 560)? (With kernel 4.13.0+ "rocm_agent_enumerator" reports my GPU, with 4.17-rc3 not).

**Comment by farnoy** [comment]
@fxkamd Can we get an update on what has been upstreamed so far? For example, can one build the rocm ecosystem from source and use with 4.17 kernel on Polaris & Fiji? Can one also run it on Vega if they use 4.18 HEAD (now that Linus merged the DRM pull request)? Are those things possible, or does something else need to be upstreamed before we're able to use ROCm outside of Ubuntu and pre-built packages?

**Comment by fxkamd** [comment]
I think your summary is basically correct. But note that current ROCm releases (1.8.x) are not compatible with the upstream ioctl interfaces. You'll need to wait for ROCm 1.9 or use my hacked WIP Thunk branch with the correct ioctl interfaces.

There are also some features still missing upstream: VM fault handling, CU masking, graphics interop, power management optimizations, some debug features, etc.

**Comment by justxi** [comment]
@fxkamd Using your WIP Thunk branch ("fxkamd/drm-next-wip") and 1.8.x branches of ROCR-Runtime and ROCm-OpenCL-Runtime  "rocm_agent_enumerator" (gfx000, gfx003) and "clinfo" (OpenCL 2.0 AMD-APP.internal (2574.0)) seems to work with kernel 4.17.2 on Gentoo.

**Comment by justxi** [comment]
With the mainline kernel 4.18.0-rc2, WIP Thunk branch ("fxkamd/drm-next-wip") and 1.8.x branches of ROCR-Runtime and ROCm-OpenCL-Runtime I get the following results:
- rocm_agent_enumerator reports my Radeon 560 (gfx803)
- clinfo reports expected information about this card

Examples:
- "HelloWorld" from "OpenCL Programming Guide" reports "Executed succesfully"
- "vector_copy" reports "... succeeded"
- "saxpy" reports "0 errors"

**Comment by kentrussell** [comment]
Closing the original issue since README.md is not present anymore. If the issue persists, create a new bug report so we can track it and help you out. Good luck!
