### ISSUE TITLE
Update GitHub description

### ISSUE THREAD

**Issue by paulmenzel** [RadeonOpenCompute/ROCK-Kernel-Driver#43]
Currently, the description is *Boltzmann Initiative: Kernel Driver* which is not very informative.

**Comment by gstoner** [comment]
Check it now the KFD needed to update it.

**Comment by paulmenzel** [comment]
Thank you for the quick reaction.

> AMDGPU Driver with KFD used by the ROCm project Also contain the current Linux Kernel that matches this base driver

Maybe add a period after *project*. Should an *s* be added to *contain*?
