### ISSUE TITLE
AMD R9 M280X FOR ASUS N551ZU

### ISSUE THREAD

**Issue by APakrohk** [RadeonOpenCompute/ROCK-Kernel-Driver#45]
Hardware is wrong.

![screenshot_2018-02-11_14-26-30](https://user-images.githubusercontent.com/27810360/36072620-ca92ac20-0f37-11e8-8cb1-30782e993c05.png)

--------------
Asus website
https://www.asus.com/Laptops/N551ZU/
--------------
lspci -mm

`
00:00.0 "Host bridge" "Advanced Micro Devices, Inc. [AMD]" "Family 15h (Models 30h-3fh) Processor Root Complex" "Advanced Micro Devices, Inc. [AMD]" "Family 15h (Models 30h-3fh) Processor Root Complex" 00:00.2 "IOMMU" "Advanced Micro Devices, Inc. [AMD]" "Family 15h (Models 30h-3fh) I/O Memory Management Unit" "Advanced Micro Devices, Inc. [AMD]" "Family 15h (Models 30h-3fh) I/O Memory Management Unit" 00:01.0 "VGA compatible controller" "Advanced Micro Devices, Inc. [AMD/ATI]" "Kaveri [Radeon R7 Graphics]" "ASUSTeK Computer Inc." "Kaveri [Radeon R7 Graphics]" 00:01.1 "Audio device" "Advanced Micro Devices, Inc. [AMD/ATI]" "Kaveri HDMI/DP Audio Controller" "ASUSTeK Computer Inc." "Kaveri HDMI/DP Audio Controller" 00:02.0 "Host bridge" "Advanced Micro Devices, Inc. [AMD]" "Device 1424" "" "" 00:02.1 "PCI bridge" "Advanced Micro Devices, Inc. [AMD]" "Device 1425" "" "" 00:03.0 "Host bridge" "Advanced Micro Devices, Inc. [AMD]" "Device 1424" "" "" 00:03.1 "PCI bridge" "Advanced Micro Devices, Inc. [AMD]" "Family 15h (Models 30h-3fh) Processor Root Port" "" "" 00:03.2 "PCI bridge" "Advanced Micro Devices, Inc. [AMD]" "Family 15h (Models 30h-3fh) Processor Root Port" "" "" 00:04.0 "Host bridge" "Advanced Micro Devices, Inc. [AMD]" "Device 1424" "" "" 00:10.0 "USB controller" "Advanced Micro Devices, Inc. [AMD]" "FCH USB XHCI Controller" -r09 -p30 "ASUSTeK Computer Inc." "FCH USB XHCI Controller" 00:10.1 "USB controller" "Advanced Micro Devices, Inc. [AMD]" "FCH USB XHCI Controller" -r09 -p30 "ASUSTeK Computer Inc." "FCH USB XHCI Controller" 00:11.0 "SATA controller" "Advanced Micro Devices, Inc. [AMD]" "FCH SATA Controller [IDE mode]" -r40 -p01 "ASUSTeK Computer Inc." "FCH SATA Controller [IDE mode]" 00:12.0 "USB controller" "Advanced Micro Devices, Inc. [AMD]" "FCH USB OHCI Controller" -r11 -p10 "ASUSTeK Computer Inc." "FCH USB OHCI Controller" 00:12.2 "USB controller" "Advanced Micro Devices, Inc. [AMD]" "FCH USB EHCI Controller" -r11 -p20 "ASUSTeK Computer Inc." "FCH USB EHCI Controller" 00:13.0 "USB controller" "Advanced Micro Devices, Inc. [AMD]" "FCH USB OHCI Controller" -r11 -p10 "ASUSTeK Computer Inc." "FCH USB OHCI Controller" 00:13.2 "USB controller" "Advanced Micro Devices, Inc. [AMD]" "FCH USB EHCI Controller" -r11 -p20 "ASUSTeK Computer Inc." "FCH USB EHCI Controller" 00:14.0 "SMBus" "Advanced Micro Devices, Inc. [AMD]" "FCH SMBus Controller" -r16 "ASUSTeK Computer Inc." "FCH SMBus Controller" 00:14.2 "Audio device" "Advanced Micro Devices, Inc. [AMD]" "FCH Azalia Controller" -r01 "ASUSTeK Computer Inc." "FCH Azalia Controller" 00:14.3 "ISA bridge" "Advanced Micro Devices, Inc. [AMD]" "FCH LPC Bridge" -r11 "ASUSTeK Computer Inc." "FCH LPC Bridge" 00:14.4 "PCI bridge" "Advanced Micro Devices, Inc. [AMD]" "FCH PCI Bridge" -r40 -p01 "" "" 00:18.0 "Host bridge" "Advanced Micro Devices, Inc. [AMD]" "Family 15h (Models 30h-3fh) Processor Function 0" "" "" 00:18.1 "Host bridge" "Advanced Micro Devices, Inc. [AMD]" "Family 15h (Models 30h-3fh) Processor Function 1" "" "" 00:18.2 "Host bridge" "Advanced Micro Devices, Inc. [AMD]" "Family 15h (Models 30h-3fh) Processor Function 2" "" "" 00:18.3 "Host bridge" "Advanced Micro Devices, Inc. [AMD]" "Family 15h (Models 30h-3fh) Processor Function 3" "" "" 00:18.4 "Host bridge" "Advanced Micro Devices, Inc. [AMD]" "Family 15h (Models 30h-3fh) Processor Function 4" "" "" 00:18.5 "Host bridge" "Advanced Micro Devices, Inc. [AMD]" "Family 15h (Models 30h-3fh) Processor Function 5" "" "" 01:00.0 "Display controller" "Advanced Micro Devices, Inc. [AMD/ATI]" "Bonaire PRO [Radeon R9 M270X]" -rff -pff "" "" 02:00.0 "Network controller" "Intel Corporation" "Wireless 7260" -rbb "Intel Corporation" "Dual Band Wireless-N 7260" 03:00.0 "Unassigned class [ff00]" "Realtek Semiconductor Co., Ltd." "RTL8411B PCI Express Card Reader" -r01 "ASUSTeK Computer Inc." "RTL8411B PCI Express Card Reader" 03:00.1 "Ethernet controller" "Realtek Semiconductor Co., Ltd." "RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller" -r12 "ASUSTeK Computer Inc." "RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller"
`

---------------
**There is no problem in Windows**
---------------
Distribute me Xubuntu

**Comment by kentrussell** [comment]
Can you get me the device ID for the GPU? 6646 should be the M280X while 6647 should be the M270X (at least according to https://pci-ids.ucw.cz/read/PC/1002 .

**Comment by APakrohk** [comment]
**lspci -n**
```
00:00.0 0600: 1022:1422
00:00.2 0806: 1022:1423
00:01.0 0300: 1002:130c
00:01.1 0403: 1002:1308
00:02.0 0600: 1022:1424
00:02.1 0604: 1022:1425
00:03.0 0600: 1022:1424
00:03.1 0604: 1022:1426
00:03.2 0604: 1022:1426
00:04.0 0600: 1022:1424
00:10.0 0c03: 1022:7814 (rev 09)
00:10.1 0c03: 1022:7814 (rev 09)
00:11.0 0106: 1022:7801 (rev 40)
00:12.0 0c03: 1022:7807 (rev 11)
00:12.2 0c03: 1022:7808 (rev 11)
00:13.0 0c03: 1022:7807 (rev 11)
00:13.2 0c03: 1022:7808 (rev 11)
00:14.0 0c05: 1022:780b (rev 16)
00:14.2 0403: 1022:780d (rev 01)
00:14.3 0601: 1022:780e (rev 11)
00:14.4 0604: 1022:780f (rev 40)
00:18.0 0600: 1022:141a
00:18.1 0600: 1022:141b
00:18.2 0600: 1022:141c
00:18.3 0600: 1022:141d
00:18.4 0600: 1022:141e
00:18.5 0600: 1022:141f
01:00.0 0380: 1002:6647
02:00.0 0280: 8086:08b1 (rev bb)
03:00.0 ff00: 10ec:5287 (rev 01)
03:00.1 0200: 10ec:8168 (rev 12)
```
ooh sorry i didn't knew

**Comment by APakrohk** [comment]
![gpuz_m280x png](https://user-images.githubusercontent.com/27810360/45483616-f91cbc00-b740-11e8-940c-bd01ddaae614.png)

**Comment by kentrussell** [comment]
Note that there are 768 shaders reported. That aligns with GPU-Z's description of the M270X (https://www.techpowerup.com/gpudb/2582/radeon-r9-m270x), as the M280X has 896 shaders (https://www.techpowerup.com/gpudb/2807/radeon-r9-m280x for 2GB and https://www.techpowerup.com/gpudb/2581/radeon-r9-m280x for 4GB). They don't have a listing for an M270X (Saturn Pro) with 4 GB VRAM as you have, so they likely defaulted to the M280X, even though that's a Saturn XT chip. 

The big issue with mobile chips is that they are all adapted to suit the laptop manufacturer's requirements, but that laptop has a Saturn Pro in it based on the PCI ID and the number of shaders. Check GPU-Zs database, the only R9 M2XX chip with 768  shaders is the 270X. 

GPU-Z might need an update to update its database (they are on 2.10 now, 0.8.2 is 3yrs old now). Try update it and see if it still says 280X after
