### ISSUE TITLE
journalctl spammed with strange messages

### ISSUE THREAD

**Issue by Brisse89** [RadeonOpenCompute/ROCK-Kernel-Driver#48]
Hi!
I'm running ROCm on Debian Unstable (aka. Sid) and because the DKMS-module doesn't work on my default kernel I've managed to get ROCm working by installing everything from the Ubuntu-repo except DKMS and just compiled the kernel from here instead. Everything seems to work fine, but when I check journalctl I see messages like this being spammed about 10 times per second or so. This does not happen when I boot my distros default kernel.

```
mar 23 16:26:44 kristoffer-debian-desktop kernel: evbug: Event. Dev: input3, Type: 0, Code: 0, Value: 0
mar 23 16:26:44 kristoffer-debian-desktop kernel: evbug: Event. Dev: input2, Type: 4, Code: 4, Value: 207
mar 23 16:26:44 kristoffer-debian-desktop kernel: evbug: Event. Dev: input2, Type: 1, Code: 107, Value: 1
mar 23 16:26:44 kristoffer-debian-desktop kernel: evbug: Event. Dev: input2, Type: 0, Code: 0, Value: 0
mar 23 16:26:44 kristoffer-debian-desktop kernel: evbug: Event. Dev: input2, Type: 4, Code: 4, Value: 207
mar 23 16:26:44 kristoffer-debian-desktop kernel: evbug: Event. Dev: input2, Type: 1, Code: 107, Value: 0
mar 23 16:26:44 kristoffer-debian-desktop kernel: evbug: Event. Dev: input2, Type: 0, Code: 0, Value: 0
```

**Comment by fxkamd** [comment]
Looks like you compiled the kernel with CONFIG_INPUT_EVBUG enabled:
config INPUT_EVBUG
        tristate "Event debugging"
        help
          Say Y here if you have a problem with the input subsystem and
          want all events (keypresses, mouse movements), to be output to
          the system log. While this is useful for debugging, it's also
          a security threat - your keypresses include your passwords, of
          course.

          If unsure, say N.

          To compile this driver as a module, choose M here: the
          module will be called evbug.

See also this related thread on Ubuntu forums: https://ubuntuforums.org/showthread.php?t=1162100
