### ISSUE TITLE
amdkfd needs CONFIG_UNUSED_SYMBOLS=y

### ISSUE THREAD

**Issue by olesalscheider** [RadeonOpenCompute/ROCK-Kernel-Driver#49]
Without `CONFIG_UNUSED_SYMBOLS=y`, amdgpu cannot find amdkfd (with current mainline HEAD at least).
Specifically, `symbol_request(kgd2kfd_init)` in `amdgpu_amdkfd_init` returns `NULL` because it cannot find the symbol.  I guess the symbol has to be added somewhere so that it does not get deleted when `CONFIG_UNUSED_SYMBOLS=n`.

**Comment by fxkamd** [comment]
I guess KFD is incombatible with CONFIG_UNUSED_SYMBOLS=n. amdgpu depends on being able to symbol_request(kgd2kfd_init) to avoid circular module dependencies between amdgpu and amdkfd.

**Comment by olesalscheider** [comment]
I understand that the symbol should not get deleted.

But the documentation of `CONFIG_UNUSED_SYMBOLS` says something about that you should write to LKML if you think that you have a symbol that should not be deleted. So I wondered if there maybe is a list of symbols to keep, even when that option is enabled...

**Comment by fxkamd** [comment]
That documentation has been there since 2006 and so far nobody has removed any symbols.

**Comment by olesalscheider** [comment]
Ok... I'm not saying that you should change anything about the way it works now.

It would just be good if `CONFIG_UNUSED_SYMBOLS=y` could be forced or if there was some documentation saying that it is needed or ...
It took me one or two hours to find out that this was the problem, and it would be nice if we can avoid that experience for others.

**Comment by kentrussell** [comment]
We do enforce this with the arch/x86/configs/rock-rel_defconfig kernel config file , which we use when doing a monolithic kernel build for Ubuntu. You can refer to that config file for any config options that may be included. Since there are literally hundreds, it would be hard to document each one that needs to be used, but that file should be useful enough to refer to going forward.

**Comment by fxkamd** [comment]
I think this problem will go away soon. We're merging KFD into amdgpu, so we'll no longer depend on unused symbols.
