### ISSUE TITLE
Supported hardware update...

### ISSUE THREAD

**Issue by harerama** [RadeonOpenCompute/ROCK-Kernel-Driver#5]
Hi, 

Do you have additional information about supported hardware ?
Are there specific features required (in the motherboard or cpu) ?
Ideally I would like a system with an Intel Skylake CPU and a dGPU (Nano) - would you have any recommendation to make about supported motherboard ?

The Z97-PRO motherboard said to work is not compatible with newer CPUs.

Thanks for your help

**Comment by gstoner** [comment]
Please look at https://radeonopencompute.github.io/hardware.html

GFX8: Radeon R9 Nano, Radeon R9 Fury,, Radeon R9 Fury X, and FirePro S9300 x2 with revolutionary HBM memories with 512 GB/s per ASIC. Currently the highest efficiency of 46 GFLOPS/watt. R9 Nano is 8 Tflops and S9300x2 support solid 14.9 Tflops of single precision performance to attack Machine Learning, Molecular Dynamics, Energy, and Signal Processing Problems

CPU Support: ROCm requires CPU's with PCIe Gen3 Atomics supports such as the Intel Xeon E5 v3 or newer Xeon processors. It will also support consumer class CPU such as the Haswell class Intel Core CPU processors or newer. We know your going to ask, yes ROCm is optimized to pull all the rich new capabilities out of the new AMD Zen based processors.
