### ISSUE TITLE
Crossfire via DisplayPort

### ISSUE THREAD

**Issue by nikolobok** [RadeonOpenCompute/ROCK-Kernel-Driver#51]
I am interested is multi-gpu crossfire via external interconnection Displayport could be still used, especially for Vega?
Looking to build fully virtualized gpu cluster using SR-IOV, where cpu used only for bootstrap.

**Comment by kentrussell** [comment]
We don't support CrossFire via DisplayPort. You can look at https://rocm-documentation.readthedocs.io/en/latest/ and https://rocm.github.io/ to see what we are able to do with ROCm in terms of trying to build that cluster,
