### ISSUE TITLE
Polaris GPU support: Radeon RX480

### ISSUE THREAD

**Issue by oscarbg** [RadeonOpenCompute/ROCK-Kernel-Driver#6]
Hi,
wanting to buy AMD Polaris RX480 card coming this month to developer with Radeon Open COmpute framework but as of now is Fiji dGPU only..
as Polaris should be more advanced than Fiji can we exepct even "unofficial" support for this GPU i.e. not officially supported but working anyway?
thanks..

**Comment by gstoner** [comment]
If what your doing is for pure compute. And you ok with 4 GB of memory., Currently the R9 Nano for compute is one fastest cards on the market especially at its power level. 175 watts. 8.19 Tflops 46 gflops per watt  500 GB/S  memory bandwidth.

RX480 is 150 watts of power 5+ tflops. 256GB/S memory bandwidth  8 GB of memory.




Get Outlook for iOS<https://aka.ms/o0ukef>




On Fri, Jun 3, 2016 at 4:06 PM -0700, "Oscar Barenys" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
wanting to buy AMD Polaris RX480 card coming this month to developer with Radeon Open COmpute framework but as of now is Fiji dGPU only..
as Polaris should be more advanced than Fiji can we exepct even "unofficial" support for this GPU i.e. not officially supported but working anyway?
thanks..

-

**Comment by oscarbg** [comment]
thanks..
but still not clear from answer if Polaris GPUs will be supported by RadeonOpenCompute stack..
as said more interested "to start" evaluating a $200 card then if more interested could switch to Nano or wait for even more powerful cards next year (Vega?)..

**Comment by gstoner** [comment]
We will have RX480 support in version 1.3 of ROCm

**Comment by gstoner** [comment]
ROCm 1.3 will have RX480 support
