### ISSUE TITLE
Updated firmware

### ISSUE THREAD

**Issue by sclarkson** [RadeonOpenCompute/ROCK-Kernel-Driver#60]
I see that the firmware supplied by the rock-dkms package is different from what's in the linux-firmware git repo. I have experienced segfaults and kernel panics using older firmware.

Is the rock-dkms package currently the only place to obtain the updated firmware?

**Comment by jlgreathouse** [comment]
Yes, at this time the `rock-dkms` package is the source for updated firmware for the ROCm version of the `amdgpu` driver. If you are using the driver provided by the `rock-dkms` package (or building a monolithic kernel from the source code provided in this git repository), then you should use the firmware from the `rock-dkms` package. The interface between our driver and firmware can change between firmware versions, so you may not be able to use the firmware located in the linux-firmware git alongside the driver code contained here.

As an aside, note that I also include a tarball with the firmware extracted from the `rock-dkms` package as part of the [Experimental ROC](https://github.com/RadeonOpenCompute/Experimental_ROC) repo. See [this folder](https://github.com/RadeonOpenCompute/Experimental_ROC/tree/roc-2.0.0/distro_install_scripts/shared_files/shared_rock_files), for instance.
