### ISSUE TITLE
Rocm 2.0 Unknown symbol __devcgroup_check_permission 

### ISSUE THREAD

**Issue by djygithub** [RadeonOpenCompute/ROCK-Kernel-Driver#68]
Hello,

Just started getting the title message (January 4, 2019) for new bare-metal ubuntu 16.04.5/rocm2.X installs.  rocm kernel is built, GPUs are not recognized.  Thought it was a hardware failure, have the same issue with two machines. Backed off to rocm 1.9.2.307 and the GPUs are recognized, rocm works.  Any ideas?  Here's the vbios:

Adapter  0    (BN=1C, DN=00, PCIID=68601002, SSID=0C351002)
    Asic Family        :  Vega10
    Flash Type         :  M25P80      (1024 KB)
    Product Name       :  Vega10 D05131 64Mx128 852e/945m
    Bios Config File   :  D0513100.006
    Bios P/N           :  113-D0513100-006
    Bios Version       :  016.001.001.000.009640
    Bios Date          :  06/11/18 17:16
    ROM Image Type     :  Legacy Image
    ROM Image Details  :
        Image[0]: Size(65024 Bytes), Type(Legacy Image)

Thanks

**Comment by jlgreathouse** [comment]
What kernel version are you running on these systems? In addition, when you're running the ROCm 2.0 install, what is the status of `dkms status` and `dmesg | grep kfd` after a reboot?

**Comment by djygithub** [comment]
Hello again,

The machines are at work I will grab dkms status and dmesg in the morning, thanks for the prompt response. It's a 4.15 kernel.

Ubuntu 16.04.5 LTS (GNU/Linux 4.15.0-041500-generic x86_64)

Thanks

**Comment by djygithub** [comment]
Before 2.0 install

Last login: Tue Jan  8 07:31:22 2019 from 10.217.79.91
rocm@rocmp2p2:~ dmesg | grep kfd
[   15.762869] kfd kfd: Initialized module
[   18.609221] kfd kfd: Allocated 3969056 bytes on gart
[   18.609616] kfd kfd: added device 1002:6860
[   20.468025] kfd kfd: Allocated 3969056 bytes on gart
[   20.468641] kfd kfd: added device 1002:6860
rocm@rocmp2p2:~ dkms status
amdgpu, 1.9-307, 4.15.0-041500-generic, x86_64: installed
rocm@rocmp2p2:~

After 2.0 install

Last login: Tue Jan  8 07:55:58 2019 from 10.217.79.91
rocm@rocmp2p2:~ dmesg | grep kfd
rocm@rocmp2p2:~ dkms status
amdgpu, 2.0-89, 4.15.0-041500-generic, x86_64: installed
rocm@rocmp2p2:~ dmesg | grep amdgpu
[   12.579543] amdgpu: Unknown symbol __devcgroup_check_permission (err 0)
[   13.697389] amdgpu: Unknown symbol __devcgroup_check_permission (err 0)
[   98.413159] amdgpu: Unknown symbol __devcgroup_check_permission (err 0)
[   98.535565] amdgpu: Unknown symbol __devcgroup_check_permission (err 0)
rocm@rocmp2p2:~ dpkg -l | grep rocm
ii  procmail                              3.22-26                                amd64        Versatile e-mail processor
ii  rocm-clang-ocl                        0.4.0-e605688                          amd64        OpenCL compilation with clang compiler.
ii  rocm-dev                              2.0.89                                 amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocm-device-libs                      0.0.1                                  amd64        Radeon Open Compute - device libraries
ii  rocm-dkms                             2.0.89                                 amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocm-opencl                           1.2.0-2018121317                       amd64        OpenCL/ROCm
ii  rocm-opencl-dev                       1.2.0-2018121317                       amd64        OpenCL/ROCm
ii  rocm-smi                              1.0.0-95-g3512a29                      amd64        System Management Interface for ROCm
ii  rocm-utils                            2.0.89                                 amd64        Radeon Open Compute (ROCm) Runtime software stack
ii  rocminfo                              1.0.0                                  amd64        Radeon Open Compute (ROCm) Runtime rocminfo tool

rocm@rocmp2p2:~ apt show rocm-libs
Package: rocm-libs
Version: 2.0.89
Priority: optional
Section: devel
Maintainer: Advanced Micro Devices Inc.
Installed-Size: 1,024 B
Depends: rocfft, rocrand, hipblas, rocblas
Homepage: https://github.com/RadeonOpenCompute/ROCm
Download-Size: 770 B
APT-Sources: http://repo.radeon.com/rocm/apt/debian xenial/main amd64 Packages
Description: Radeon Open Compute (ROCm) Runtime software stack

rocm@rocmp2p2:~

I will try a new vbios next, any suggestions?  The one I am using seesm to be the most current for this board:

Adapter  0    (BN=3D, DN=00, PCIID=68601002, SSID=0C351002)
    Asic Family        :  Vega10
    Flash Type         :  M25P80      (1024 KB)
    Product Name       :  Vega10 D05131 64Mx128 852e/945m
    Bios Config File   :  D0513100.006
    Bios P/N           :  113-D0513100-006
    Bios Version       :  016.001.001.000.009640
    Bios Date          :  06/11/18 17:16
    ROM Image Type     :  Legacy Image
    ROM Image Details  :
        Image[0]: Size(65024 Bytes), Type(Legacy Image)

Thanks

**Comment by djygithub** [comment]
finger check

**Comment by fxkamd** [comment]
The symbol should be defined in kcl_device_croup.c, which is part of the amdkcl subdirectory in the DKMS source. I don't know what it's not including that in your build.

Your kernel version looks a bit unusual. Is that a custom kernel build?

**Comment by jlgreathouse** [comment]
I think it's the [mainline Linux 4.15.0 build](https://kernel.ubuntu.com/~kernel-ppa/mainline/v4.15/) rather than the later HWE releases from Ubuntu.

I'll note that I run into this error as well with amdgpu/2.0-89 when running against this particular kernel build. The `amdkcl` module loads, but the `amdgpu` module refuses to load because of the `Unknown symbol __devcgroup_check_permission` error.

**Comment by djygithub** [comment]
It's what you get after installing 16.04.5 base, then apt dist-upgrade, then sudo do-release-upgrade:

New release '18.04.1 LTS' available.
Run 'do-release-upgrade' to upgrade to it.


Last login: Mon Jan  7 10:19:45 2019
rocm@rocmp2p2:~ dmesg | grep taint
[    9.694677] amdkcl: loading out-of-tree module taints kernel.
[    9.694677] amdkcl: loading out-of-tree module taints kernel.
[    9.694704] amdkcl: module verification failed: signature and/or required key missing - tainting kernel
rocm@rocmp2p2:~ dmesg | grep kfd
rocm@rocmp2p2:~ dmesg | grep amd
[    9.694677] amdkcl: loading out-of-tree module taints kernel.
[    9.694677] amdkcl: loading out-of-tree module taints kernel.
[    9.694704] amdkcl: module verification failed: signature and/or required key missing - tainting kernel
[   10.460067] amdgpu: Unknown symbol __devcgroup_check_permission (err 0)
[   11.609526] amdgpu: Unknown symbol __devcgroup_check_permission (err 0)
[   99.185901] amdgpu: Unknown symbol __devcgroup_check_permission (err 0)
[  100.206397] amdgpu: Unknown symbol __devcgroup_check_permission (err 0)
rocm@rocmp2p2:~ sudo do-release-upgrade
[sudo] password for rocm:
Checking for a new Ubuntu release
Get:1 Upgrade tool signature [819 B]
Get:2 Upgrade tool [1,263 kB]
Fetched 1,264 kB in 0s (0 B/s)
authenticate 'bionic.tar.gz' against 'bionic.tar.gz.gpg'
extracting 'bionic.tar.gz'

Reading cache

Thanks

**Comment by djygithub** [comment]
i am not in a hurry, let's proceed with RCA.

**Comment by djygithub** [comment]
Here's where I got the 4.15.00 kernel [https://www.ostechnix.com/install-linux-kernel-4-15-rpm-deb-based-systems/](url) I will try 4.15.0-43-generic thanks

**Comment by djygithub** [comment]
Upgrading to the 4.15.0-43-generic kernel did the trick much obliged!
sudo apt-get install linux-generic-hwe-16.04
rocm@rocmp2p2:~ dmesg | grep kfd
[   15.087541] kfd kfd: Allocated 3969056 bytes on gart
[   15.087803] kfd kfd: added device 1002:6860
[   16.839042] kfd kfd: Allocated 3969056 bytes on gart
[   16.839516] kfd kfd: added device 1002:6860
rocm@rocmp2p2:~ dkms status
amdgpu, 2.0-89, 4.15.0-041500-generic, x86_64: installed
amdgpu, 2.0-89, 4.15.0-43-generic, x86_64: installed
rocm@rocmp2p2:~

Thanks again.

**Comment by jlgreathouse** [comment]
Hi @djkurtz 

I have attached a [zip file containing a patch](https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/files/2746239/rock-dkms-2.0_upstream-kernel-4.15.patch.zip) that should get the `rock-dkms` driver working on mainline (4.15.00) kernels. This fixes the problem in the driver that is also fixed by the Ubuntu HWE kernels. The Ubuntu HWE kernels make a required API call "open" to modules, while the mainline kernel does not. This patch bypasses the problem.

To apply this patch for ROCm 2.0, you can do the following:

1. Install the `rock-dkms` package (e.g. `sudo apt install rocm-dkms` or `sudo apt install rock-dkms`)
1. Download and unzip the patch (e.g. put `rock-dkms-2.0_upstream-kernel-4.15.patch.zip` in your home directory, and then run `unzip ~/rock-dkms-2.0_upstream-kernel-4.15.patch.zip`
1. Go to the DKMS module source code directory (e.g. `cd /usr/src/amdgpu-2.0-89`
1. Apply the patch (`sudo patch -p 1 < ~/rock-dkms-2.0_upstream-kernel-4.15.patch`
1. Rebuild/reinstall the dkms module (`sudo dkms remove amdgpu/2.0-89 --all; sudo dkms add amdgpu/2.0-89; sudo dkms build amdgpu/2.0-89; sudo dkms install amdgpu/2.0-89`)
1. Reboot

This patch should be applied to our DKMS module for the next release of ROCm as well. Thanks.
