### ISSUE TITLE
amdgpu support (slightly off topic - sorry)

### ISSUE THREAD

**Issue by mattmacy** [RadeonOpenCompute/ROCK-Kernel-Driver#7]
I apologize in advance - I know that this isn't the right place for this. However, it's also a critical intermediate step to getting ROCK going on my R9 Nano and Fury X. And I've had success here before. 

Googling is not bringing up an obvious amd equivalent of intel-gfx. Is there such a thing?

I'm trying to bring up the Linux 4.6 amdgpu driver essentially unmodified on FreeBSD using FreeBSD's linuxkpi compatibility shims on a Carrizo (thinkpad e545). I've gotten the 4.6 i915 driver working virtually everywhere using the same approach so there aren't glaring holes in the shims. Nonetheless, the bugs are in the shims, but manifest as driver failures and it's often difficult to trace problems back to linuxkpi shortcomings.

At this instant uvd_v6_0_ring_test_ring is failing - see output below. The driver has made it through the first 10 ring tests and uvd_v6_0_start. At first glance there's nothing obviously different about uvd_v6. Any pointers / suggestions would be much appreciated.

Thanks in advance.

Jun 6 08:00:03 trainwreck kernel: [drm] initializing kernel modesetting (CARRIZO 0x1002:0x9874 0x0000:0x0000 0x00).
Jun 6 08:00:03 trainwreck kernel: [drm] register mmio base: 0xF1400000
Jun 6 08:00:03 trainwreck kernel: [drm] register mmio size: 262144
Jun 6 08:00:03 trainwreck kernel: [drm] doorbell mmio base: 0xF0000000
Jun 6 08:00:03 trainwreck kernel: [drm] doorbell mmio size: 8388608
Jun 6 08:00:03 trainwreck kernel: [drm] probing gen 2 caps for device 1002:9874 = 0/0
Jun 6 08:00:03 trainwreck kernel: [drm] probing mlw for device 1002:9874 = 0
Jun 6 08:00:03 trainwreck kernel: [drm:amdgpu_get_bios] ATOMBIOS detected
Jun 6 08:00:03 trainwreck kernel: ATOM BIOS: BR46529.100
Jun 6 08:00:03 trainwreck kernel: [drm:amdgpu_atom_allocate_fb_scratch] atom firmware requested 000fffe0 32kb
Jun 6 08:00:03 trainwreck kernel: [drm:gmc_v8_0_init_microcode] 
Jun 6 08:00:03 trainwreck kernel: drmn0: VRAM: 1024M 0x0000000000000000 - 0x000000003FFFFFFF (1024M used)
Jun 6 08:00:03 trainwreck kernel: drmn0: GTT: 1024M 0x0000000040000000 - 0x000000007FFFFFFF
Jun 6 08:00:03 trainwreck kernel: [drm] Detected VRAM RAM=1024M, BAR=256M
Jun 6 08:00:03 trainwreck kernel: [drm] RAM width 64bits UNKNOWN
Jun 6 08:00:03 trainwreck kernel: Zone kernel: Available graphics memory: 3625188 kiB
Jun 6 08:00:03 trainwreck kernel: Zone dma32: Available graphics memory: 2097152 kiB
Jun 6 08:00:03 trainwreck kernel: Initializing pool allocator
Jun 6 08:00:03 trainwreck kernel: [drm] amdgpu: 1024M of VRAM memory ready
Jun 6 08:00:03 trainwreck kernel: [drm] amdgpu: 1024M of GTT memory ready.
Jun 6 08:00:03 trainwreck kernel: [drm] GART: num cpu pages 262144, num gpu pages 262144
Jun 6 08:00:03 trainwreck kernel: [drm] PCIE GART of 1024M enabled (table at 0x0000000000040000).
Jun 6 08:00:03 trainwreck kernel: [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
Jun 6 08:00:03 trainwreck kernel: [drm] Driver supports precise vblank timestamp query.
Jun 6 08:00:03 trainwreck kernel: drmn0: amdgpu: using MSI.
Jun 6 08:00:03 trainwreck kernel: [drm:drm_irq_install] irq=43
Jun 6 08:00:03 trainwreck kernel: [drm] amdgpu: irq initialized.
Jun 6 08:00:03 trainwreck kernel: [drm] amdgpu: dpm initialized
Jun 6 08:00:03 trainwreck kernel: [drm] Connector eDP-1: get mode from tunables:
Jun 6 08:00:03 trainwreck kernel: [drm] - kern.vt.fb.modes.eDP-1
Jun 6 08:00:03 trainwreck kernel: [drm] - kern.vt.fb.default_mode
Jun 6 08:00:03 trainwreck kernel: [drm:drm_sysfs_connector_add] adding "eDP-1" to sysfs
Jun 6 08:00:03 trainwreck kernel: [drm:drm_sysfs_hotplug_event] generating hotplug event
Jun 6 08:00:03 trainwreck kernel: [drm] Connector DP-1: get mode from tunables:
Jun 6 08:00:03 trainwreck kernel: [drm] - kern.vt.fb.modes.DP-1
Jun 6 08:00:03 trainwreck kernel: [drm] - kern.vt.fb.default_mode
Jun 6 08:00:03 trainwreck kernel: [drm:drm_sysfs_connector_add] adding "DP-1" to sysfs
Jun 6 08:00:03 trainwreck kernel: [drm:drm_sysfs_hotplug_event] generating hotplug event
Jun 6 08:00:03 trainwreck kernel: [drm] Connector DP-2: get mode from tunables:
Jun 6 08:00:03 trainwreck kernel: [drm] - kern.vt.fb.modes.DP-2
Jun 6 08:00:03 trainwreck kernel: [drm] - kern.vt.fb.default_mode
Jun 6 08:00:03 trainwreck kernel: [drm:drm_sysfs_connector_add] adding "DP-2" to sysfs
Jun 6 08:00:03 trainwreck kernel: [drm:drm_sysfs_hotplug_event] generating hotplug event
Jun 6 08:00:03 trainwreck kernel: [drm] AMDGPU Display Connectors
Jun 6 08:00:03 trainwreck kernel: [drm] Connector 0:
Jun 6 08:00:03 trainwreck kernel: [drm] eDP-1
Jun 6 08:00:03 trainwreck kernel: [drm] HPD1
Jun 6 08:00:03 trainwreck kernel: [drm] DDC: 0x4868 0x4868 0x4869 0x4869 0x486a 0x486a 0x486b 0x486b
Jun 6 08:00:03 trainwreck kernel: [drm] Encoders:
Jun 6 08:00:03 trainwreck kernel: [drm] LCD1: INTERNAL_UNIPHY
Jun 6 08:00:03 trainwreck kernel: [drm] Connector 1:
Jun 6 08:00:03 trainwreck kernel: [drm] DP-1
Jun 6 08:00:03 trainwreck kernel: [drm] HPD2
Jun 6 08:00:03 trainwreck kernel: [drm] DDC: 0x486c 0x486c 0x486d 0x486d 0x486e 0x486e 0x486f 0x486f
Jun 6 08:00:03 trainwreck kernel: [drm] Encoders:
Jun 6 08:00:03 trainwreck kernel: [drm] DFP1: INTERNAL_UNIPHY
Jun 6 08:00:03 trainwreck kernel: [drm] Connector 2:
Jun 6 08:00:03 trainwreck kernel: [drm] DP-2
Jun 6 08:00:03 trainwreck kernel: [drm] HPD3
Jun 6 08:00:03 trainwreck kernel: [drm] DDC: 0x4870 0x4870 0x4871 0x4871 0x4872 0x4872 0x4873 0x4873
Jun 6 08:00:03 trainwreck kernel: [drm] Encoders:
Jun 6 08:00:03 trainwreck kernel: [drm] DFP2: INTERNAL_UNIPHY1
Jun 6 08:00:03 trainwreck kernel: [drm:gfx_v8_0_init_microcode] 
Jun 6 08:00:03 trainwreck kernel: drmn0: fence driver on ring 0 use gpu addr 0x0000000040000010, cpu addr 0x0xfffff801240db010
Jun 6 08:00:03 trainwreck kernel: drmn0: fence driver on ring 1 use gpu addr 0x0000000040000020, cpu addr 0x0xfffff801240db020
Jun 6 08:00:03 trainwreck kernel: drmn0: fence driver on ring 2 use gpu addr 0x0000000040000030, cpu addr 0x0xfffff801240db030
Jun 6 08:00:03 trainwreck kernel: drmn0: fence driver on ring 3 use gpu addr 0x0000000040000040, cpu addr 0x0xfffff801240db040
Jun 6 08:00:03 trainwreck kernel: drmn0: fence driver on ring 4 use gpu addr 0x0000000040000050, cpu addr 0x0xfffff801240db050
Jun 6 08:00:03 trainwreck kernel: drmn0: fence driver on ring 5 use gpu addr 0x0000000040000060, cpu addr 0x0xfffff801240db060
Jun 6 08:00:03 trainwreck kernel: drmn0: fence driver on ring 6 use gpu addr 0x0000000040000070, cpu addr 0x0xfffff801240db070
Jun 6 08:00:03 trainwreck kernel: drmn0: fence driver on ring 7 use gpu addr 0x0000000040000080, cpu addr 0x0xfffff801240db080
Jun 6 08:00:03 trainwreck kernel: drmn0: fence driver on ring 8 use gpu addr 0x0000000040000090, cpu addr 0x0xfffff801240db090
Jun 6 08:00:03 trainwreck kernel: [drm:sdma_v3_0_init_microcode] 
Jun 6 08:00:03 trainwreck kernel: drmn0: fence driver on ring 9 use gpu addr 0x00000000400000a0, cpu addr 0x0xfffff801240db0a0
Jun 6 08:00:03 trainwreck kernel: drmn0: fence driver on ring 10 use gpu addr 0x00000000400000b0, cpu addr 0x0xfffff801240db0b0
Jun 6 08:00:03 trainwreck kernel: [drm] Found UVD firmware Version: 1.80 Family ID: 11
Jun 6 08:00:03 trainwreck kernel: drmn0: fence driver on ring 11 use gpu addr 0x0000000000281ac0, cpu addr 0x0xfffff800e0281ac0
Jun 6 08:00:03 trainwreck kernel: [drm] Found VCE firmware Version: 50.17 Binary ID: 3
Jun 6 08:00:03 trainwreck kernel: drmn0: fence driver on ring 12 use gpu addr 0x00000000400000d0, cpu addr 0x0xfffff801240db0d0
Jun 6 08:00:03 trainwreck kernel: drmn0: fence driver on ring 13 use gpu addr 0x00000000400000e0, cpu addr 0x0xfffff801240db0e0
Jun 6 08:00:03 trainwreck kernel: [drm:amdgpu_ih_process] amdgpu_ih_process: rptr 0, wptr 48
Jun 6 08:00:03 trainwreck kernel: [drm:dce_v11_0_pageflip_irq] amdgpu_crtc->pflip_status = 0 != AMDGPU_FLIP_SUBMITTED(2)
Jun 6 08:00:03 trainwreck last message repeated 2 times
Jun 6 08:00:03 trainwreck kernel: [drm] ring test on 0 succeeded in 4 usecs
Jun 6 08:00:03 trainwreck kernel: [drm] ring test on 1 succeeded in 8 usecs
Jun 6 08:00:03 trainwreck kernel: [drm] ring test on 2 succeeded in 4 usecs
Jun 6 08:00:03 trainwreck kernel: [drm] ring test on 3 succeeded in 2 usecs
Jun 6 08:00:03 trainwreck kernel: [drm] ring test on 4 succeeded in 2 usecs
Jun 6 08:00:03 trainwreck kernel: [drm] ring test on 5 succeeded in 2 usecs
Jun 6 08:00:03 trainwreck kernel: [drm] ring test on 6 succeeded in 2 usecs
Jun 6 08:00:03 trainwreck kernel: [drm] ring test on 7 succeeded in 1 usecs
Jun 6 08:00:03 trainwreck kernel: [drm] ring test on 8 succeeded in 2 usecs
Jun 6 08:00:03 trainwreck kernel: [drm] ring test on 9 succeeded in 2 usecs
Jun 6 08:00:03 trainwreck kernel: [drm] ring test on 10 succeeded in 2 usecs
Jun 6 08:00:57 trainwreck syslogd: kernel boot file is /boot/kernel/kernel
Jun 6 08:00:57 trainwreck kernel: [drm:0xffffffff829a41a7s] _ERROR_ amdgpu: ring 11 test failed (0xCAFEDEAD)

**Comment by arodrigx7** [comment]
Hey Matt,

Sorry for the late reply. My recommendation in this scenario would be to try to validate that the GFX rings are working correctly first. You should be able to use the ip_block_mask module parameter to boot with the UVD (and possibly VCE) engines disabled.

Once you know that GFX is actually working correctly, you can move to investigating the issue itself with UVD initialization. Try with the power management features disabled first as that should rule out most of the complex bug cases for UVD.

After you've tried the above you should have a better idea about the nature of the bug.

A good place to discuss these type of issues in the dri-devel mailing list, there are a lot of people more knowledgeable than I am in this topic that frequently interact on that list.

**Comment by mattmacy** [comment]
Thanks. I got the same advice there as I got here. The problem I have with dri-devel is that it's super high traffic with 90+% of it unrelated to amdgpu so it's going to be  harder to hold a thread than a dedicated platform list like intel-gfx.

**Comment by arodrigx7** [comment]
Hey Matt,

I'm curious if the new 1.2 release would help at all with this issue. If there is anything else you need let us know.

**Comment by mattmacy** [comment]
It turns out that FreeBSD's efifb either breaks amdgpu on Carrizo or needs to be disabled earlier in attach. By disabling it at boot I'm able to successfully attach amdgpu on my Thinkpad e545 (A10).

Thanks.

**Comment by johnbridgman** [comment]
BTW we recently set up an amd-gfx mailing list, which is probably more like what you are looking for.

Don't think we have all of the developers signed up to it yet, but we have a critical mass.

**Comment by jlgreathouse** [comment]
Checked with @iotamudelta. It looks like amdgpu works with `graphics/drm-devel-kmod` as of Linux 4.16 thanks to the OP. Re-closing ticket.
