### ISSUE TITLE
Trying to install on ubuntu 19.10 - fails

### ISSUE THREAD

**Issue by paulathomas** [RadeonOpenCompute/ROCK-Kernel-Driver#85]
I have tried to install rocm (and therefore rock) from the standard radeon repositories (I know they are for 18.04 LTS but that should still work{ish}) I got the attached error log from dpkg:
[make.log](https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/files/3934831/make.log)
 
Is there any way forward other than going back to 18.04 (which I am not prepared to do)?

**Comment by fxkamd** [comment]
You're trying to build ROCk against a 5.3 kernel. This is not supported yet.

**Comment by paulathomas** [comment]
OK, I will try downloading the source and see if I can make it happen.

**Comment by kentrussell** [comment]
Did you have any luck with that? Or with the 3.3 build? We're supporting the 5.3 kernel in 18.04, so it should be worth a try

**Comment by kentrussell** [comment]
Closing since we supported the 5.3 kernel in previous releases.
