### ISSUE TITLE
HD5870/HD5970 support in ubuntu 18.04??

### ISSUE THREAD

**Issue by erosenst** [RadeonOpenCompute/ROCK-Kernel-Driver#86]
Is there any support plan for HD5870/5970 cards? They are quite new and powerfull ones.. 
I find that Ubuntu 18.04(3) don't support XFX HD5870 at all. It drops to use FB device. No OpenCL etc.

HD5870     FP64      544.0 GFLOPS         FP32    2.720 TFLOPS
HD5970     FP64      464.0 GFLOPS x2    FP32    2.320 TFLOPS x2
RX5700XT FP64      609.6 GFLOPS         FP32    9.754 TFLOPS 

Thank you

**Comment by kentrussell** [comment]
The 5870 (Cyprus) and 5970 (Hemlock) are not new cards, as they are both over 10 years old (released in late 2009) and as such are not supported under ROCm. You can refer to https://rocm.github.io/hardware.html for a list of supported GPUs for reference.
