### ISSUE TITLE
What does TCC and TA mean?

### ISSUE THREAD

**Issue by WenbinHou** [RadeonOpenCompute/ROCK-Kernel-Driver#88]
Don't know if this is a good place to place this question, but I can find lots of "TA" and "TCC" in kernel driver's code. 

When using rocm profiler, there are a lot of basic HW counters like "TA_TA_BUSY" or "TCC_HIT".
I really can't find what "TA" and "TCC" stand for.

Thanks for any help from anyone!

**Comment by jlgreathouse** [comment]
TCC stands for "Texture Cache per Channel", which is our hardware's terminology for our L2 data cache. See [this slide deck for more deatils](http://www.m5sim.org/wiki/images/f/fd/AMD_gem5_APU_simulator_micro_2015_final.pptx).

TA is the texture address unit, part of the L1 data cache used to handle addressing into the data arrays.
