### ISSUE TITLE
Wrong chip name is being picked up

### ISSUE THREAD

**Issue by mirh** [RadeonOpenCompute/ROCK-Kernel-Driver#89]
Hoping this is the right bug tracker for amdkfd...

I know southern island doesn't work with the driver (lack of user mode queues or something), and that's why you get the nice "not supported in kfd" message on boot. 
But my card is being spelled as "VERDE" rather than "CAPE VERDE" here.

**Comment by kentrussell** [comment]
For KFD, the upstream bugtracker is what you'd be looking for https://gitlab.freedesktop.org/drm/amd/-/issues . 

Is this actually an issue? The kernel code only uses single-words for GPU identification (Verde, Vega10, Fiji, etc), and there are no Verde cards that aren't Cape Verde cards. In general, they try to use a single word (or they squash them together if it's a word and number, like vega10 or Polaris20) , but Verde/CapeVerde is the only 2-word GPU that has a unique identifier (New Zealand uses the Tahiti identifier)

**Comment by mirh** [comment]
Well, never mind then¿
