### ISSUE TITLE
Windows support (driver, runtime etc)

### ISSUE THREAD

**Issue by ugahugo** [RadeonOpenCompute/ROCK-Kernel-Driver#9]
See subj.

Wondering why AMD always releases their frameworks on Linux / Unix platforms only.

Guys, do you have in mind that GPGPU developers can't build their products for Windows users (98% of them in mass markets)?

This problem relates to the problem of compiling C++11 - compatible code for AMD GPU as well. I see that AMD puts a lot of efforts to use HIP infrastructure to build nvcc - compatible code (with its own C++ implementation) but all of these efforts are useless considering no Windows support. Yet.

**Comment by gstoner** [comment]
Feature Request noted with Product management team for HCC support on Windows
