### ISSUE TITLE
GPU TLB shootdown latency

### ISSUE THREAD

**Issue by trinayan** [RadeonOpenCompute/ROCK-Kernel-Driver#91]
Hi,

I am a developer of the publicly available AMD GCN3 simulator MGPUSim which is developed at Northeastern University. I am looking to model the TLB shootdown latency for the R9Nano GPU. But I am unable to find this information online or in the ROCK driver code. So is there any data on the TLB shootdown latency for ROCM supported GPUs?. Is it comparable to CPUs?. Are there any publicly available benchmarks or microbenchmarks to test this latency?. Thanks.

Best,
Trinayan

**Comment by jlgreathouse** [comment]
Hi @trinayan 

Sorry for the delay in responding to this, but I don't believe AMD plans to make information about our TLB shootdown latencies available to the public.
