### ISSUE TITLE
Distro and Kernel compatibility

### ISSUE THREAD

**Issue by agravgaard** [RadeonOpenCompute/ROCK-Kernel-Driver#94]
# 1: Unhandled linux distributions

`DRM_VER` will only be defined for a hardcoded selection of OS names. 
For an OS name is not in that selection the dkms compilation will fail, i.e. the `OS_NAME = "unknown"` case.
However, by providing a default (e.g. in a final else condition of the dkms [Makefile](https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/blob/2106edaef95ae2262097652454bce1fe720b2b9b/drivers/gpu/drm/amd/dkms/Makefile#L28-L43)) would solve this for most linux distributions. A suggestion for this change is in #95 commit 8d62d90 

The default would just be the same case as under some other OS names. Assuming that `$(kdir)` is defined and that it contains a Makefile with `VERSION` and `PATCHLEVEL`

# 2: 5.7+ Kernel

The above suggested change (see #95 ) allows successful dkms compile with 4.19 and 5.6 but not 5.7
Because [pci_platform_rom was removed in 5.7](https://github.com/torvalds/linux/commit/86845e37aca4c80eace290a727a49caa8390febb)

So I would like to request that the upstream changes for 5.7, i.e. the linked commit, would be merged into ROCk. As in #95 commit 3630276

## Relevant issues and pull requests:
* #95 
* #65 ( & [641 in ROCm](https://github.com/RadeonOpenCompute/ROCm/issues/641)) Unhandled OS names
* #90 
* [244 in rocm-arch](https://github.com/rocm-arch/rocm-arch/pull/244)

**Comment by kentrussell** [comment]
This was resolved in 11f359924d drm/amdkcl: add various os support, which was back before ROCm 4.5
