### ISSUE TITLE
What GPUs are supported?

### ISSUE THREAD

**Issue by taichichuan** [RadeonOpenCompute/ROCK-Kernel-Driver#97]
Sorry to raise this as an issue, but I can't seem to find what devices are actually supported by ROCm.  I've tried the Raven Rock (GFX902) with dismal results.  The ROCm 2.6 code actually ran the TensorFlow test suite slower than running on the bare CPU.  And, BruhnSpace will not publish the changes they used to get thing running on the GFX906.  So, that appears to be a dead end.  Are there any APUs that are supported be ROCm?  If so, what part numbers?  If not APUs are supported, then what GPU families *are* supported?

**Comment by xuhuisheng** [comment]
please ref here:
https://github.com/RadeonOpenCompute/ROCm/#Hardware-and-Software-Support

**Comment by kentrussell** [comment]
Closing as link provided is the most up-to-date regarding support. Note that partial (untested) support for other GPUs/APUs is possible, so your experience may change, but we have a finite amount of lab space for testing, so we cannot test every APU/GPU and combination of each.
