### ISSUE TITLE
OOPs output from 5.6.0-kfd

### ISSUE THREAD

**Issue by taichichuan** [RadeonOpenCompute/ROCK-Kernel-Driver#98]
I just cloned the ROCK-Kernel-Driver repo and rebuilt with the rock-dbg_defconfig config file using Ubuntu 18.04.  The board is the Udoo Bolt (V1605B CPU).  Can anyone make any suggestions as to how to address these Kernel OOPs?

Everything looks good until this series of OOPs occurred:

[    2.819617] Adding 2097148k swap on /swapfile.  Priority:-2 extents:6 across:2260988k SSFS
[    2.863078] [drm] amdgpu kernel modesetting enabled.
[    2.863083] [drm] amdgpu version: 5.6.5
[    2.863085] [drm] OS DRM version: 5.6.0
[    2.863948] amdgpu: Topology: Add APU node [0x0:0x0]
[    2.870678] amdgpu 0000:05:00.0: vgaarb: deactivate vga console
[    2.871136] amdgpu 0000:05:00.0: enabling device (0006 -> 0007)
[    2.871297] [drm] initializing kernel modesetting (RAVEN 0x1002:0x15DD 0x1002:0x15DD 0x83).
[    2.871308] amdgpu 0000:05:00.0: amdgpu: Trusted Memory Zone (TMZ) feature disabled as experimental (default)
[    2.874783] [drm] register mmio base: 0xFE700000
[    2.874788] [drm] register mmio size: 524288
[    2.874816] [drm] add ip block number 0 <soc15_common>
[    2.874819] [drm] add ip block number 1 <gmc_v9_0>
[    2.874821] [drm] add ip block number 2 <vega10_ih>
[    2.874823] [drm] add ip block number 3 <psp>
[    2.874825] [drm] add ip block number 4 <gfx_v9_0>
[    2.874828] [drm] add ip block number 5 <sdma_v4_0>
[    2.874830] [drm] add ip block number 6 <powerplay>
[    2.874832] [drm] add ip block number 7 <dm>
[    2.874834] [drm] add ip block number 8 <vcn_v1_0>
[    2.878081] amdgpu: ATOM BIOS: 113-RAVEN-113
[    2.878473] [drm] VCN decode is enabled in VM mode
[    2.878475] [drm] VCN encode is enabled in VM mode
[    2.878477] [drm] JPEG decode is enabled in VM mode
[    2.878694] [drm] vm size is 262144 GB, 4 levels, block size is 9-bit, fragment size is 9-bit
[    2.878716] amdgpu 0000:05:00.0: amdgpu: VRAM: 1024M 0x000000F400000000 - 0x000000F43FFFFFFF (1024M used)
[    2.878720] amdgpu 0000:05:00.0: amdgpu: GART: 1024M 0x0000000000000000 - 0x000000003FFFFFFF
[    2.878724] amdgpu 0000:05:00.0: amdgpu: AGP: 267419648M 0x000000F800000000 - 0x0000FFFFFFFFFFFF
[    2.878733] [drm] Detected VRAM RAM=1024M, BAR=1024M
[    2.878736] [drm] RAM width 128bits DDR4
[    2.882041] [TTM] Zone  kernel: Available graphics memory: 3554608 KiB
[    2.882054] [TTM] Zone   dma32: Available graphics memory: 2097152 KiB
[    2.882056] [TTM] Initializing pool allocator
[    2.882084] [TTM] Initializing DMA pool allocator
[    2.882562] [drm] amdgpu: 1024M of VRAM memory ready
[    2.882578] [drm] amdgpu: 6942M of GTT memory ready.
[    2.882587] [drm] GART: num cpu pages 262144, num gpu pages 262144
[    2.883141] [drm] PCIE GART of 1024M enabled (table at 0x000000F400900000).
[    2.897089] amdgpu: [powerplay] hwmgr_sw_init smu backed is smu10_smu
[    2.900393] [drm] Found VCN firmware Version ENC: 1.9 DEC: 1 VEP: 0 Revision: 28
[    2.900430] [drm] PSP loading VCN firmware
[    2.924274] random: crng init done
[    2.924278] random: 7 urandom warning(s) missed due to ratelimiting
[    2.925133] [drm] reserve 0x400000 from 0xf43fc00000 for PSP TMR
[    3.139400] amdgpu 0000:05:00.0: amdgpu: RAS: optional ras ta ucode is not available
[    3.169201] [drm] kiq ring mec 2 pipe 1 q 0
[    3.170403] ------------[ cut here ]------------
[    3.170509] WARNING: CPU: 5 PID: 1734 at drivers/gpu/drm/amd/amdgpu/../display/dc/bios/command_table_helper2.c:75 dal_bios_parser_init_cmd_tbl_helper2+0x44/0x50 [amdgpu]
[    3.170510] Modules linked in: amdgpu(+) amd_iommu_v2 gpu_sched ttm k10temp video ip_tables x_tables i2c_piix4
[    3.170519] CPU: 5 PID: 1734 Comm: systemd-udevd Not tainted 5.6.0-kfd #1
[    3.170520] Hardware name: Seco C40/C40, BIOS 1.05 R.C. 8 08/30/2019
[    3.170615] RIP: 0010:dal_bios_parser_init_cmd_tbl_helper2+0x44/0x50 [amdgpu]
[    3.170617] Code: 00 00 48 89 03 b8 01 00 00 00 5b c3 e8 85 1d 00 00 48 89 03 b8 01 00 00 00 5b c3 e8 16 25 00 00 48 89 03 b8 01 00 00 00 5b c3 <0f> 0b 31 c0 5b c3 66 0f 1f 44 00 00 0f 1f 44 00 00 48 85 f6 74 0e
[    3.170619] RSP: 0018:ffffbc5f405d7820 EFLAGS: 00010202
[    3.170621] RAX: 0000000000000000 RBX: ffff96a541964800 RCX: ffffbc5f405d7817
[    3.170622] RDX: 0000000000000001 RSI: 000000000000000a RDI: ffff96a5419648a8
[    3.170624] RBP: ffff96a541964800 R08: ffff96a546580000 R09: 000000000000d000
[    3.170625] R10: ffff96a54658005c R11: 0000000000009364 R12: 000000000000000a
[    3.170626] R13: ffff96a55676bbc0 R14: ffffbc5f405d78a0 R15: ffff96a54b8c0000
[    3.170628] FS:  00007fd8658bb680(0000) GS:ffff96a557f40000(0000) knlGS:0000000000000000
[    3.170629] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[    3.170631] CR2: 00007f47b001fe88 CR3: 0000000213a88000 CR4: 00000000003406e0
[    3.170632] Call Trace:
[    3.170725]  firmware_parser_create+0x18c/0x750 [amdgpu]
[    3.170816]  dal_bios_parser_create+0x11/0x30 [amdgpu]
[    3.170903]  dc_create+0x470/0x6a0 [amdgpu]
[    3.170909]  ? rcu_read_lock_sched_held+0x52/0x80
[    3.170994]  ? amdgpu_cgs_create_device+0x23/0x50 [amdgpu]
[    3.171084]  amdgpu_dm_init+0x15f/0x1390 [amdgpu]
[    3.171089]  ? find_held_lock+0x2d/0x90
[    3.171171]  ? smum_send_msg_to_smc_with_parameter+0x88/0xf0 [amdgpu]
[    3.171265]  dm_hw_init+0xe/0x20 [amdgpu]
[    3.171334]  amdgpu_device_init+0x1277/0x1cf0 [amdgpu]
[    3.171418]  amdgpu_driver_load_kms+0x48/0x1f0 [amdgpu]
[    3.171488]  amdgpu_pci_probe+0x124/0x200 [amdgpu]
[    3.171493]  local_pci_probe+0x3d/0x90
[    3.171497]  pci_device_probe+0x108/0x1c0
[    3.171502]  really_probe+0xe6/0x420
[    3.171505]  driver_probe_device+0x110/0x120
[    3.171509]  device_driver_attach+0x4f/0x60
[    3.171511]  __driver_attach+0x99/0x130
[    3.171514]  ? device_driver_attach+0x60/0x60
[    3.171516]  bus_for_each_dev+0x76/0xc0
[    3.171519]  bus_add_driver+0x147/0x220
[    3.171521]  ? 0xffffffffc07f3000
[    3.171524]  driver_register+0x5b/0xf0
[    3.171526]  ? 0xffffffffc07f3000
[    3.171529]  do_one_initcall+0x5a/0x2e0
[    3.171532]  ? do_init_module+0x22/0x219
[    3.171534]  ? rcu_read_lock_sched_held+0x52/0x80
[    3.171538]  ? kmem_cache_alloc_trace+0x2a5/0x2d0
[    3.171540]  ? do_init_module+0x22/0x219
[    3.171543]  do_init_module+0x5b/0x219
[    3.171545]  load_module+0x2392/0x2c00
[    3.171555]  ? __do_sys_finit_module+0xe9/0x110
[    3.171557]  __do_sys_finit_module+0xe9/0x110
[    3.171564]  do_syscall_64+0x4a/0x1d0
[    3.171568]  entry_SYSCALL_64_after_hwframe+0x49/0xbe
[    3.171570] RIP: 0033:0x7fd8653ff959
[    3.171573] Code: 00 f3 c3 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 40 00 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d ff f4 2c 00 f7 d8 64 89 01 48
[    3.171574] RSP: 002b:00007ffe79b3b228 EFLAGS: 00000246 ORIG_RAX: 0000000000000139
[    3.171576] RAX: ffffffffffffffda RBX: 0000558c5ac5fe50 RCX: 00007fd8653ff959
[    3.171578] RDX: 0000000000000000 RSI: 00007fd8650de105 RDI: 0000000000000011
[    3.171579] RBP: 00007fd8650de105 R08: 0000000000000000 R09: 00007ffe79b3b340
[    3.171580] R10: 0000000000000011 R11: 0000000000000246 R12: 0000000000000000
[    3.171582] R13: 0000558c5ac51f70 R14: 0000000000020000 R15: 0000558c5ac5fe50
[    3.171588] irq event stamp: 107542
[    3.171591] hardirqs last  enabled at (107541): [<ffffffff98279098>] get_page_from_freelist+0xd88/0x1790
[    3.171593] hardirqs last disabled at (107542): [<ffffffff98001d9a>] trace_hardirqs_off_thunk+0x1a/0x1c
[    3.171595] softirqs last  enabled at (107318): [<ffffffff9900032c>] __do_softirq+0x32c/0x430
[    3.171598] softirqs last disabled at (107209): [<ffffffff9807bc63>] irq_exit+0xb3/0xc0
[    3.171599] ---[ end trace 06b7945e94c2b723 ]---
[    3.171925] [drm] DM_PPLIB: values for F clock
[    3.171927] [drm] DM_PPLIB:   400000 in kHz, 3174 in mV
[    3.171928] [drm] DM_PPLIB:   933000 in kHz, 3724 in mV
[    3.171930] [drm] DM_PPLIB:   1067000 in kHz, 3924 in mV
[    3.171931] [drm] DM_PPLIB:   1200000 in kHz, 4074 in mV
[    3.171933] [drm] DM_PPLIB: values for DCF clock
[    3.171934] [drm] DM_PPLIB:   300000 in kHz, 3174 in mV
[    3.171937] [drm] DM_PPLIB:   600000 in kHz, 3724 in mV
[    3.171938] [drm] DM_PPLIB:   626000 in kHz, 3924 in mV
[    3.171940] [drm] DM_PPLIB:   654000 in kHz, 4074 in mV
[    3.172336] [drm] Display Core initialized with v3.2.87!
[    3.172354] BUG: kernel NULL pointer dereference, address: 0000000000000000
[    3.172363] #PF: supervisor read access in kernel mode
[    3.172369] #PF: error_code(0x0000) - not-present page
[    3.172374] PGD 0 P4D 0
[    3.172379] Oops: 0000 [#1] SMP NOPTI
[    3.172385] CPU: 5 PID: 1734 Comm: systemd-udevd Tainted: G        W         5.6.0-kfd #1
[    3.172392] Hardware name: Seco C40/C40, BIOS 1.05 R.C. 8 08/30/2019
[    3.172502] RIP: 0010:enable_disp_power_gating_v2_1+0x48/0x150 [amdgpu]
[    3.172511] Code: 24 58 31 c0 48 8b 83 a8 00 00 00 48 c7 44 24 04 00 00 00 00 48 8d 74 24 03 48 c7 44 24 0c 00 00 00 00 c7 44 24 14 00 00 00 00 <ff> 10 84 c0 0f 84 e2 00 00 00 0f b6 44 24 03 89 ef 88 44 24 04 48
[    3.172529] RSP: 0018:ffffbc5f405d7810 EFLAGS: 00010246
[    3.172538] RAX: 0000000000000000 RBX: ffff96a541964800 RCX: 0000000000000001
[    3.172550] RDX: 0000000000000002 RSI: ffffbc5f405d7813 RDI: 0000000000000001
    3.172560] RBP: 0000000000000002 R08: ffffbc5f405d7874 R09: 0000000000000000
[    3.172566] R10: 0000000000000000 R11: 0000000000000000 R12: ffff96a54abc0000
[    3.172572] R13: 0000000000000001 R14: 0000000000000007 R15: ffff96a552377380
[    3.172579] FS:  00007fd8658bb680(0000) GS:ffff96a557f40000(0000) knlGS:0000000000000000
[    3.172586] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[    3.172592] CR2: 0000000000000000 CR3: 0000000213a88000 CR4: 00000000003406e0
[    3.172598] Call Trace:
[    3.172689]  ? generic_reg_get+0x1d/0x30 [amdgpu]
[    3.172782]  dcn10_bios_golden_init+0x53/0xf0 [amdgpu]
[    3.172874]  dcn10_init_hw+0xda/0xd20 [amdgpu]
[    3.172970]  amdgpu_dm_init+0x203/0x1390 [amdgpu]
[    3.172980]  ? find_held_lock+0x2d/0x90
[    3.173067]  ? smum_send_msg_to_smc_with_parameter+0x88/0xf0 [amdgpu]
[    3.173164]  dm_hw_init+0xe/0x20 [amdgpu]
[    3.173237]  amdgpu_device_init+0x1277/0x1cf0 [amdgpu]
[    3.173313]  amdgpu_driver_load_kms+0x48/0x1f0 [amdgpu]
[    3.173386]  amdgpu_pci_probe+0x124/0x200 [amdgpu]
[    3.173394]  local_pci_probe+0x3d/0x90
[    3.173400]  pci_device_probe+0x108/0x1c0
[    3.173408]  really_probe+0xe6/0x420
[    3.173414]  driver_probe_device+0x110/0x120
[    3.173420]  device_driver_attach+0x4f/0x60
[    3.173425]  __driver_attach+0x99/0x130
[    3.173431]  ? device_driver_attach+0x60/0x60
[    3.173436]  bus_for_each_dev+0x76/0xc0
[    3.173442]  bus_add_driver+0x147/0x220
[    3.173447]  ? 0xffffffffc07f3000
[    3.173452]  driver_register+0x5b/0xf0
[    3.173457]  ? 0xffffffffc07f3000
[    3.173462]  do_one_initcall+0x5a/0x2e0
[    3.173469]  ? do_init_module+0x22/0x219
[    3.173475]  ? rcu_read_lock_sched_held+0x52/0x80
[    3.173482]  ? kmem_cache_alloc_trace+0x2a5/0x2d0
[    3.173487]  ? do_init_module+0x22/0x219
[    3.173493]  do_init_module+0x5b/0x219
[    3.173498]  load_module+0x2392/0x2c00
[    3.173507]  ? __do_sys_finit_module+0xe9/0x110
[    3.173512]  __do_sys_finit_module+0xe9/0x110
[    3.173521]  do_syscall_64+0x4a/0x1d0
[    3.173528]  entry_SYSCALL_64_after_hwframe+0x49/0xbe
[    3.173534] RIP: 0033:0x7fd8653ff959
[    3.173539] Code: 00 f3 c3 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 40 00 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d ff f4 2c 00 f7 d8 64 89 01 48
[    3.173554] RSP: 002b:00007ffe79b3b228 EFLAGS: 00000246 ORIG_RAX: 0000000000000139
[    3.173561] RAX: ffffffffffffffda RBX: 0000558c5ac5fe50 RCX: 00007fd8653ff959
[    3.173568] RDX: 0000000000000000 RSI: 00007fd8650de105 RDI: 0000000000000011
[    3.173574] RBP: 00007fd8650de105 R08: 0000000000000000 R09: 00007ffe79b3b340
[    3.173580] R10: 0000000000000011 R11: 0000000000000246 R12: 0000000000000000
[    3.173587] R13: 0000558c5ac51f70 R14: 0000000000020000 R15: 0000558c5ac5fe50
[    3.173595] Modules linked in: amdgpu(+) amd_iommu_v2 gpu_sched ttm k10temp video ip_tables x_tables i2c_piix4
[    3.173609] CR2: 0000000000000000
[    3.173615] ---[ end trace 06b7945e94c2b724 ]---
[    3.423597] RIP: 0010:enable_disp_power_gating_v2_1+0x48/0x150 [amdgpu]
[    3.423601] Code: 24 58 31 c0 48 8b 83 a8 00 00 00 48 c7 44 24 04 00 00 00 00 48 8d 74 24 03 48 c7 44 24 0c 00 00 00 00 c7 44 24 14 00 00 00 00 <ff> 10 84 c0 0f 84 e2 00 00 00 0f b6 44 24 03 89 ef 88 44 24 04 48
[    3.423631] RSP: 0018:ffffbc5f405d7810 EFLAGS: 00010246
[    3.423639] RAX: 0000000000000000 RBX: ffff96a541964800 RCX: 0000000000000001
[    3.423647] RDX: 0000000000000002 RSI: ffffbc5f405d7813 RDI: 0000000000000001
[    3.423654] RBP: 0000000000000002 R08: ffffbc5f405d7874 R09: 0000000000000000
[    3.423661] R10: 0000000000000000 R11: 0000000000000000 R12: ffff96a54abc0000
[    3.423669] R13: 0000000000000001 R14: 0000000000000007 R15: ffff96a552377380
[    3.423678] FS:  00007fd8658bb680(0000) GS:ffff96a557f40000(0000) knlGS:0000000000000000
[    3.423688] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[    3.423694] CR2: 0000000000000000 CR3: 0000000213a88000 CR4: 00000000003406e0
[    3.423704] BUG: sleeping function called from invalid context at ./include/linux/percpu-rwsem.h:38
[    3.423715] in_atomic(): 0, irqs_disabled(): 1, non_block: 0, pid: 1734, name: systemd-udevd
[    3.423724] INFO: lockdep is turned off.
[    3.423730] irq event stamp: 107692
[    3.423740] hardirqs last  enabled at (107691): [<ffffffff980f54e5>] console_unlock+0x4c5/0x5a0
[    3.423753] hardirqs last disabled at (107692): [<ffffffff98001d9a>] trace_hardirqs_off_thunk+0x1a/0x1c
[    3.423770] softirqs last  enabled at (107564): [<ffffffff9900032c>] __do_softirq+0x32c/0x430
[    3.423782] softirqs last disabled at (107545): [<ffffffff9807bc63>] irq_exit+0xb3/0xc0
[    3.423794] CPU: 5 PID: 1734 Comm: systemd-udevd Tainted: G      D W         5.6.0-kfd #1
[    3.423805] Hardware name: Seco C40/C40, BIOS 1.05 R.C. 8 08/30/2019
[    3.423814] Call Trace:
[    3.423824]  dump_stack+0x71/0x9b
[    3.423832]  ___might_sleep+0x15a/0x240
[    3.423840]  exit_signals+0x30/0x2d0
[    3.423848]  do_exit+0xb0/0xc10
[    3.423855]  rewind_stack_do_exit+0x17/0x20
[    3.716530] Generic FE-GE Realtek PHY r8169-400:00: attached PHY driver [Generic FE-GE Realtek PHY] (mii_bus:phy_addr=r8169-400:00, irq=IGNORE)
[    3.840180] r8169 0000:04:00.0 enp4s0: Link is Down
[    4.949403] fuse: init (API version 7.31)
[    4.949463] *** VALIDATE fuseblk ***
[    4.949472] *** VALIDATE fuse ***
[    5.228092] xfsettingsd[2475]: segfault at 18 ip 00007f29c2c27337 sp 00007ffd2107e610 error 4 in libxklavier.so.16.4.0[7f29c2c17000+19000]
[    5.228119] Code: 4c 89 e7 e8 0b 56 ff ff 48 89 03 48 8b 5c 24 30 e9 d1 fd ff ff e8 b9 5b ff ff 66 0f 1f 84 00 00 00 00 00 41 54 55 48 89 f5 53 <48> 8b 42 18 48 89 d1 49 89 fc 48 89 d3 48 89 fa 48 89 ef 48 8b b0
[    6.450780] r8169 0000:04:00.0 enp4s0: Link is Up - 1Gbps/Full - flow control rx/tx
[    6.450804] IPv6: ADDRCONF(NETDEV_CHANGE): enp4s0: link becomes ready
[    6.799798] Bridge firewalling registered

**Comment by kentrussell** [comment]
This was a Display issue that was resolved back before ROCm 4.5
