### ISSUE TITLE
I think we should update data->smu_features when we enable or disable feature by sysfs pp_features

### ISSUE THREAD

**Issue by andyzhanged** [RadeonOpenCompute/ROCK-Kernel-Driver#99]
Hi,
The sysfs pp_features provides one way to adjust what powerplay features to be enabled. When driver init,  vega20_enable_all_smu_features will be called to get pp_features and store it in data->smu_features[i].  Many code will use data->smu_features[i] as a condition to choose code path.  
```
static int vega20_enable_all_smu_features(struct pp_hwmgr *hwmgr)
{
	struct vega20_hwmgr *data =
			(struct vega20_hwmgr *)(hwmgr->backend);
	uint64_t features_enabled;
	int i;
	bool enabled;
	int ret = 0;

	PP_ASSERT_WITH_CODE((ret = smum_send_msg_to_smc(hwmgr,
			PPSMC_MSG_EnableAllSmuFeatures)) == 0,
			"[EnableAllSMUFeatures] Failed to enable all smu features!",
			return ret);

	ret = vega20_get_enabled_smc_features(hwmgr, &features_enabled);
	PP_ASSERT_WITH_CODE(!ret,
			"[EnableAllSmuFeatures] Failed to get enabled smc features!",
			return ret);

	for (i = 0; i < GNLD_FEATURES_MAX; i++) {
		enabled = (features_enabled & data->smu_features[i].smu_feature_bitmap) ?
			true : false;
		data->smu_features[i].enabled = enabled;
		data->smu_features[i].supported = enabled;

#if 0
		if (data->smu_features[i].allowed && !enabled)
			pr_info("[EnableAllSMUFeatures] feature %d is expected enabled!", i);
		else if (!data->smu_features[i].allowed && enabled)
			pr_info("[EnableAllSMUFeatures] feature %d is expected disabled!", i);
#endif
	}
	return 0;
}
```
But i read the sysfs pp_features code path, found it doesnot update data->smu_features, but other code path for example vega20_enable_fan_control_feature will update data->smu_features after enable smu_features.

```
static int vega20_enable_fan_control_feature(struct pp_hwmgr *hwmgr)
{
	struct vega20_hwmgr *data = hwmgr->backend;
	int ret = 0;

	if (data->smu_features[GNLD_FAN_CONTROL].supported) {
		ret = vega20_enable_smc_features(
				hwmgr, true,
				data->smu_features[GNLD_FAN_CONTROL].
				smu_feature_bitmap);
		PP_ASSERT_WITH_CODE(!ret,
				"Enable FAN CONTROL feature Failed!",
				return ret);
		data->smu_features[GNLD_FAN_CONTROL].enabled = true;
	}

	return ret;
}
```
So  i think maybe it is a bug.

**Comment by fxkamd** [comment]
Comment from one of our power management engineer:

> Yes, there seems a bug with the “pp_features” on Vega20. But instead of “data->smu_features[GNLD_FAN_CONTROL].supported”, the problem is “data->smu_features[GNLD_FAN_CONTROL].enabled" not updated correctly. “data->smu_features[GNLD_FAN_CONTROL].supported" is an indication whether disablement/enablement is permitted. It should not be affected by the “pp_features” sysfs.

**Comment by andyzhanged** [comment]
Yes, We only need to update data->smu_features[i].enabled. So is there a plan to fix it? thank you.

**Comment by fxkamd** [comment]
I've asked our power management expert to work on a fix. A better way to get a hold of most of the amdgpu graphics driver team directly would be on the amd-gfx@lists.freedesktop.org mailing list. On this github we're a more compute-specific team piggy-backing on the great work of the graphics driver team for a lot of the basic GPU hardware support.

**Comment by andyzhanged** [comment]
I see, thank you.
